### ISSUE TITLE
Figure out how to track web performance over time

### ISSUE THREAD

**Issue by shawnbot** [uswds/uswds#1791]
This is really an epic in its own right because there are a lot of moving parts. Some SaaS's do this out of the box, but we've agreed that it's worth looking into how we can—and would recommend that agencies:

- [ ] Track variance—e.g. between scores on a given branch and master, which is how our code coverage tracking works; or over time
- [ ] Decide if, and under which conditions, a variance fails a CI build (e.g. if the Google PageSpeed Insights score goes down by 5 points or more, or if the YSlow grade drops)
- [ ] Run through the process a couple of times to test and validate it

**Comment by shawnbot** [comment]
See previous discussions in #815.

**Comment by msecret** [comment]
A lot of performance recommendations today focus on metrics and budgets. A team will define what metrics are important for them(speed index, render start, total page weight, etc) and will set a budget for them based on type of site, how their competition compares. The build fails if the measurements go over the budgets. While not every team would require this type of setup, I definitely think linking performance to the build in this way is a great way for the team to always be thinking about performance, and to guarantee that future teams or open source contributors don't commit code that degrades performance.

**Comment by msecret** [comment]
This also makes me realize we should ask in our interviews: what does the long term maintenance of the website look like, what team will maintain this in the long term, etc.

**Comment by shawnbot** [comment]
Yeah, good points @msecret. Cc'ing @lauraponce on the interview question tip.

**Comment by msecret** [comment]
This seems promising and supposedly the tool uses lighthouse, so we could just add it to our existing setup.

https://habd.as/monitor-pwa-website-performance

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
