### ISSUE TITLE
Document long-term support plan and workflow for v1.x

### ISSUE THREAD

**Issue by shawnbot** [uswds/uswds#1916]
Before we release 2.0 we need to clearly communicate our policy for supporting the 1.x release branch.

### TODO
- [ ] Research how other, similar projects do this
- [ ] Document how we plan to do it in `RELEASE.md`
- [ ] Write it up as an update for the site

**Comment by shawnbot** [comment]
For reference: [Node.js long-term support (LTS) plan](https://github.com/nodejs/LTS#lts-plan)

**Comment by shawnbot** [comment]
So, I think there are two things that need to be decided here:

1. **Is long-term support (LTS) for major versions even applicable?** In other words, does this team want to commit to releasing bug fixes for 1.x releases after 2.0?
1. **Does a regular release schedule make sense for this team?** For instance, does it make sense to commit to releasing at least a patch or minor version every other sprint?

Re: 1), I think it's really up to us. If we don't have the time or resources to manage bug fixes (let alone new features) for 1.x _and_ 2.x, then the answer should be no. You may want to defer this decision until you really understand what types of breaking changes 2.0 will include.

Re: 2), I think that having a regular release schedule would help everyone get in the habit of releasing more often and thinking more long-term. The more often you do it, the quicker you'll get better at it.

And with that, I'll hand this issue over to @yowill. ✌️

**Comment by thisisdano** [comment]
We'll also need our plan for legacy documentation

**Comment by shawnbot** [comment]
Hi friends, I miss you! Keep up the great work. ❤️

**Comment by maya** [comment]
TODO: Add a section to our README that states we will be in maintenance mode and supporting critical bug fixes for 9 months.

**Comment by thisisdano** [comment]
@shawnbot can't heart that enough

**Comment by maya** [comment]
This is done in #3002 🎉 

We'll get a nice nav item in the sidenav of the site, once uswds/uswds-site#739 is merged.
