### ISSUE TITLE
Changing our name to more accurately describe what we are and what we do

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#2300]
This epic addresses the need to be a good player in government by being extra clear about what and who we are. We know that the word _Standards_ is a sticking point as well as a useful lever, so our challenge is to maintain our authority and identity as we change to something more accurate and less controversial.

### Issues related to this epic

- Choose a new name for the system
- Create an implementation path for the new name
- Audit all places our old name is used
- Work to change references to the old name — first in our own site, code, and documentation

**Comment by maya** [comment]
[:lock: Naming decisions doc](https://docs.google.com/document/d/1obEmQLNDhvMFuzcw6H7oxKKhae1HxZZpBpFVkA_vC5Y/edit#) is complete.

**Comment by maya** [comment]
- [ ] Decide what to change it to: U.S. Web Design System
  - [ ] Shorthand: the Design System
  - [ ] Change name and shorthand throughout main repo and docs site
- [ ] Write a blog post to explain the change as relevant to the work we’re doing and what we’re providing
  - Less about the name, more about the benefit, pedagogy — benefits of system design thinking, similar to standardization without the baggage, rigidity
- [ ] Pick a URL: designsystem.gov / designsystem.digital.gov
  - [ ] Register URL
  - [ ] Set up redirects from old URL
- [ ] Rename repo to uswds
- [ ] Establish our own GitHub org for uswds? (i.e. uswds/uswds)
  - [ ] Reach out to #github-admins
- [ ] Change our team email to uswds@gsa.gov (alt designsystem@gsa.gov)
- [ ] Change Twitter display name, #uswds and #uswds-public Slack channel description (any other social media stuff?)

**Comment by jeremyzilar** [comment]
I think this would be an opportunity to put out a few cards* for Twitter and Facebook that talk about
- The name change
- Why the U.S. Web Design System is important
- How to contribute
🇺🇸 

```
The U.S. Web Design System is ready to help you make better digital services.
Become a part of the #uswds.
```

```
Over 400 people have contributed to The U.S. Web Design System. 
Become a part of the #uswds.
```

```
Build faster, and with greater assurance using The U.S. Web Design System. 
Become a part of the #uswds.
```

```
A design system for the public.
Accessible. Flexible. Fast.
Become a part of the #uswds.
```

_* cards == jpgs with text on them_

**Comment by bruce-usab** [comment]
> * cards == jpgs with text on them

2018 and there still is no good substitute!   Just don’t forget the alt tag!

**Comment by jeremyzilar** [comment]
We can also reach out to a number of our friends in the Civic Tech space to help spread the word:
- USDS comms team
- Defense Digital Service
- Code for America

**Comment by thisisdano** [comment]
URL-wise, I think I'm leaning toward `designsystem.digital.gov` — it may not be a future-forward as `designsystem.gov`, but I like how it establishes the digital scope of our product. It doesn't oversell us.

**Comment by thisisdano** [comment]
I'm inclined to hold on too much in the way of cards and direct promo until we move to our new URL. I think our first announcement is that we _will be_ changing our name, and a link to the relevant GH issues.

Then we do all the stuff in the list above, _then_ we direct folks to the new URL and possibly the new GH org. I want these to be connected to tangible next steps, and to the more pedestrian task of re-bookmarking, etc

**Comment by gbinal** [comment]
+1 to that URL, @thisisdano.  It's a good balance.

**Comment by thisisdano** [comment]
@jeremyzilar what do we need to do to start getting moving on `designsystem.digital.gov`?

**Comment by thisisdano** [comment]
We should issue-ize those URL-related steps.

**Comment by jeremyzilar** [comment]
@maya The DNS is hosted through Route53. I can help make the change. 

**Prep**
- [ ] Figure out where the existing redirects are located
- [ ] Get an export of the existing `standards.usa.gov` DNS record

**Switch-over**
- [ ] Get the cloudfront URL from @wslack or the existing DNS setup
- [ ] Enter the Cloudfront URL into the `digitalgov.gov` terraform file
- [ ] _Wait 3 mins for it to be live at `designsystem.digital.gov`_
- [ ] Put in a redirect to `designsystem.digital.gov`
- [ ] Check to see if we need to remove old DNS entries at `usa.gov`

**Comment by maya** [comment]
@jeremyzilar Currently, `playbook.cio.gov/designstandards` redirects to `standards.usa.gov`. It may have been done by OMB CIO, but not positive. Has enough time passed from using that old URL that we maybe don't need it anymore?

**Comment by jeremyzilar** [comment]
@maya There is a 302 redirect there. We'll need to figure out where that is set, and hopefully we can add the new redirect in at that location.

**Comment by jeremyzilar** [comment]
Would we also move over `components.standards.usa.gov` to `components.designsystem.digital.gov`

**Comment by maya** [comment]
Yes, that would make sense.

**Comment by wslack** [comment]
We can run URL changes for cloudfront in two different ways:

1. New site on new cloudfront domains (I recommend this one)
    - Will makes new domains
    - You point DNS for the new URLs to the new domains
    - confirm the HTTPS got set
    - You change the URL in Federalist settings for the repo
    - You set up redirects for the old URLs, possibly using a separate federalist repo that's already scanned
    - (if needed) Will points the old cloudfront address to any redirect repos.
    - (otherwise) the old CloudFront distribution is deleted

2. New site on old cloudfront domains
    - Will updates your domains to serve for both URLs
    - You point DNS for the new URLs to the old cloudfront URLs
    - confirm the HTTPS got set
    - You change the URL in Federalist settings for the repo
    - You set up redirects for the old URLs, possibly using a separate federalist repo that's already scanned
    - (if needed) the old URL DNS is pointed at a new cloudfront address


Note that these are separate from changing the Github repo name or your org, which is currently only possible via deleting and re-adding the site to Federalist.

**Comment by maya** [comment]
This is done. Thanks to everybody who helped get this across the line.
