### ISSUE TITLE
Conduct usability tests on utilities feature

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2390]
We have some new functionality to make prototyping easier with utility classes, or single purpose classes. We should test it with designers and developers to see that it's helping them build things more easily.

[🔒Research plan](https://docs.google.com/document/d/1P-KzrkKT4660ijsAqeOmati6FnmS9v1HwNHq0P3nxyk/edit#heading=h.hhdd94ilcll0)

## Research goal
- Does the new functionality we've created help people create prototypes easily?
- Does the new functionality help people modify their existing projects easily?

## TODOs

- [x] [Recruit 3-5 people](https://drive.google.com/open?id=1Umi0_imwuRfwhio45hcU9ZOlFkIoTTy3dtvgLDytRJ4) for user testing
- [x] Write a usability testing script #2435
- [x] Schedule 45 min sessions with recruits

**Friday** 
3-4pm ET with Micah

**Tues**
1-2pm ET with Scott
4-5pm ET with Jeremy

**Wed**
2-3pm ET with Jen

**Fri**
1-2pm ET with Stephanie

**Mon 5/7**
2-3pm ET with Scott K

**Comment by maya** [comment]
How GDS does it:
>I don’t know if it’s directly applicable but we ask designers / devs from other departments to bring in 2 or 3 pages of a service that they’re currently working on and get them to recreate it in the research session.
>
>We initially asked them to recreate a page that we’d designed but we later assumed (correctly) that having the user bring in their own work to replicate we’d learn more about the kind of things people were trying to do.
>
>To avoid just copy / pasting code we asked them to send the screens ahead of time and they worked from print outs.
>
>If there was something we wanted them to do that they hadn’t naturally done in the session, we might ask them how they might swap a button for a different one or add more space between these two things…

**Comment by maya** [comment]
This is done 🎉
