### ISSUE TITLE
Create a way to try out different themes

### ISSUE THREAD

**Issue by maya** [uswds/uswds#2392]
As someone that wants to see the possibilities of the USWDS so that I can see if it's right for me or to get inspiration, I'd like to be able to see and customize a few different themes.

We could create a CodePen template with a style tile and 1-2 sample pages to see the theme implemented.

## TODOs

- [x] Create a live example on [CodePen](https://codepen.io/mbenari/pen/zWBjPr)
- [x] Use Sass maps
- [x] Add logic for secondary/accent color
- [x] Add logic for primary color - how to access nested Sass map for vivid?
- [x] Add typography controls and logic
- [ ] Add a way to use vivid variants, and in a consistent way across hues
- [ ] Add sample pages (landing page, form)

### Some ideas from  [🔒here](https://docs.google.com/presentation/d/17qzyBnI__jflmAQJSfIr9SU7Zj7Aw7G6j_IFghoYOfw/edit#slide=id.g24f9d0dd68_0_37)
<img width="788" alt="screen shot 2018-03-14 at 12 05 16 pm" src="https://user-images.githubusercontent.com/5249443/37428384-587c8484-2789-11e8-9448-54bff44de4f0.png">
<img width="780" alt="screen shot 2018-03-14 at 12 05 34 pm" src="https://user-images.githubusercontent.com/5249443/37428388-5dd632a4-2789-11e8-9bfb-3b6703ec051a.png">
<img width="785" alt="screen shot 2018-03-14 at 12 05 28 pm" src="https://user-images.githubusercontent.com/5249443/37428392-5f0813c2-2789-11e8-9b10-ae2b54d04a77.png">

**Comment by austinhernandez** [comment]
Here are mockups for NSF!
https://gsa.invisionapp.com/d/main/#/projects/prototypes/11711789

**Comment by maya** [comment]
Thanks @austinhernandez! It says "You Need Permission" so just requested access to view it.

**Comment by thisisdano** [comment]
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).
