### ISSUE TITLE
Create a card component.

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3210]
### User Story
As a front-end developer, I need a way to collect, organize, and display repeated information so that it is easier to display specific grouped units.

### Related issues
- [ ] Draft problem statement: https://github.com/uswds/uswds/issues/3148
- [ ] Landscape analysis of principles and guidance: https://github.com/uswds/uswds/issues/3161
- [ ] Landscape analysis of component design: https://github.com/uswds/uswds/issues/3162
- [ ] Draft initial assumptions: https://github.com/uswds/uswds/issues/3149
- [ ] Draft component principles: https://github.com/uswds/uswds/issues/3166

### Resources
Cards and not cards [Freehand]: https://bixal.invisionapp.com/freehand/document/xqLZnFMTR
Landscape analysis: https://github.com/uswds/uswds/wiki/Card-Landscape-Analysis
Draft principles: https://github.com/uswds/uswds/wiki/Card-Principles-(Draft)

**Comment by thisisdano** [comment]
Cards and not cards [Freehand]: https://bixal.invisionapp.com/freehand/document/xqLZnFMTR

**Comment by thisisdano** [comment]
Done
