### ISSUE TITLE
Add new page Start with Core Code

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3422]
Evergreen content. 
Discussion around this being it's own page  in `How to Use`  
Has some relationship to fundies. 
Potential for reorg around getting started content
Based on the content in the monthly call.

Content notes: More advanced than fundamentals, goes beyond to introduce packages. How to use packages to include only parts of the DS. "Fundamentals +" build on concepts of fundamentals and quick start. [See Gist](https://gist.github.com/thisisdano/7c6f117da94a3b89f7d4ecabe77a8c92) USWDS without components, just the internals. Use case: is to experiment with design tokens with out components. those who already have a design system. can start to learn the DS without rebuilding a new DS. 
Why, how, and examples/next steps. how do you incorporate code to incorporate this design language. 

**Tasks**
- [ ] draft content
- [ ] determine where this content lives and it's relationship to `Getting Started` content
- [ ] client approval
- [ ] creation and publication of page

**DOD**
- [ ] Acceptance criteria is met
- [ ] Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by afeijoo** [comment]
@KimberlyHodges Here are the existing materials to start from:

* [Github Gist](https://gist.github.com/thisisdano/7c6f117da94a3b89f7d4ecabe77a8c92)
* [Monthly call slides](https://docs.google.com/presentation/d/14sTH3UP3lOlaLKuXOUUhHRg48DsdAKG-zqu3vyz12GI/edit#slide=id.g8396f32244_0_28):lock: (starting on slide 29)
* [Monthly call captioning](https://drive.google.com/open?id=1HTgVTyJ0ZbwjfGvSaQojh1sN3JLpTjoP):lock:

**Comment by KimberlyHodges** [comment]
@afeijoo please review: [h]ttps://docs.google.com/document/d/1IpdhESmrxwOHBtQUBbH9qUM6UWwc8o-JqTiwAjEn7OM/edit?usp=sharing

**Comment by afeijoo** [comment]
LGTM! @thisisdano ready for you to take a look at [Get Started with No Code](https://docs.google.com/document/d/1IpdhESmrxwOHBtQUBbH9qUM6UWwc8o-JqTiwAjEn7OM/edit):lock:

**Comment by KimberlyHodges** [comment]
@afeijoo I've reviewed and updated my proposed intro and specifications for Start With No Code page. Can you review and send back to Dan when ready? [https://docs.google.com/document/d/1IpdhESmrxwOHBtQUBbH9qUM6UWwc8o-JqTiwAjEn7OM/edit?usp=sharing]

**Comment by KimberlyHodges** [comment]
@nks-bix the issue title should be: Add new page Start with Core Code 
Can you update please? It's not actually no code, but core code and is a new page on USWDS vs documentation. Thanks.

**Comment by afeijoo** [comment]
@katieekline I reviewed and left some suggestions and comments for you in the [draft gDoc](https://docs.google.com/document/d/1IpdhESmrxwOHBtQUBbH9qUM6UWwc8o-JqTiwAjEn7OM/edit?ts=5f0f26ac#).:lock:

**Comment by jAigret-Bix** [comment]
Core Code gist: https://gist.github.com/thisisdano/7c6f117da94a3b89f7d4ecabe77a8c92

**Comment by thisisdano** [comment]
We've included many of these ideas in the [uswds-tutorial](https://github.com/uswds/uswds-tutorial)
