### ISSUE TITLE
Draft blog post to announce Card Component

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3423]
Card Component blog

- [x] [Draft gDoc](https://docs.google.com/document/d/1_iVKAzxv-B-V0u1qoNtVo10UpEAOXXvx5x5Y5CjSm5o/edit#)
- [ ] Client review and approval
- [x] [Github page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/ja-card-blog/whats-new/updates/2020/09/28/card-component/)
- [ ] TTS Comms 
- [ ] OSC, if needed
- [ ] Publish
- [ ] Digital.gov short post

**Comment by afeijoo** [comment]
Draft in progress in [Blog: Introducing Card Component](https://drive.google.com/open?id=1_iVKAzxv-B-V0u1qoNtVo10UpEAOXXvx5x5Y5CjSm5o)

**Comment by nks-bix** [comment]
primary location:  on USWDS-news; but a crosspost elsewhere is smart too.

**Comment by KimberlyHodges** [comment]
Updated outline. Discussed approach and next steps during Friday stand up. 
[https://drive.google.com/open?id=1_iVKAzxv-B-V0u1qoNtVo10UpEAOXXvx5x5Y5CjSm5o
](url)

**Comment by KimberlyHodges** [comment]
Revised draft and need to review with @afeijoo to work on outstanding questions related to card examples, which to use, then I think it's ready for review.

**Comment by afeijoo** [comment]
@thisisdano Ready for your 👀

**Comment by afeijoo** [comment]
@katieekline Looks great! I'm reassigning this draft back to you for the next iteration.

**Comment by katieekline** [comment]
@afeijoo Thanks for the feedback! I've made changes accordingly and it is ready for your review.

**Comment by afeijoo** [comment]
@thisisdano This draft [blog post to introduce the USWDS card component](https://docs.google.com/document/d/1_iVKAzxv-B-V0u1qoNtVo10UpEAOXXvx5x5Y5CjSm5o/edit):lock: is ready for your review and approval.

**Comment by katieekline** [comment]
The copy looks good.

**Comment by jAigret-Bix** [comment]
@thisisdano [Github](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/ja-card-blog/whats-new/updates/2020/09/28/card-component/) page is ready. We need your content review. Missing a social sharing image and calls for a FAicon.

**Comment by jAigret-Bix** [comment]
@thisisdano  @katieekline Decision on 10/29: we will not publish blogs unless there is a specific comms plan needed. this blog will be edited into an Introduction paragraph and added to the top of the guidance page. A new issue will be created and this one can be closed.
