### ISSUE TITLE
Add breadcrumb component

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds#3452]
## User story
As a designer and developer I need a simple, intuitive way to communicate site hierarchy and context to users — and give them a way to navigate inside that hierarchy.

## Landscape analysis
https://github.com/uswds/uswds/issues/3405
Landscape analysis: https://bixal.invisionapp.com/freehand/document/tSS644yrC
Preliminary analysis: https://github.com/uswds/uswds/wiki/Breadcrumbs-Landscape-Analysis

## Next steps
- [ ] Get initial accessibility recommendations ([3411#issuecomment](https://github.com/uswds/uswds/issues/3411#issuecomment-631092286)) 
- [ ] Create a prototype. [#3409](https://github.com/uswds/uswds/issues/3409)
- [ ] Identify key questions and scenarios especially around small-screen/mobile usage [#1#card-38547455](https://github.com/orgs/uswds/projects/1#card-38547455)
- [ ] Collect feedback from interviews and usability [#3420](https://github.com/uswds/uswds/issues/3420)
- [ ] Perform usability testing [#3459](https://github.com/uswds/uswds/issues/3459)
- [ ] Draft guidance [#3407](https://github.com/uswds/uswds/issues/3407)
- [ ] Perform accessibility review [#3411](https://github.com/uswds/uswds/issues/3411)

### Clear
- [ ] Include a well-formed user story, preferably one that connects to research findings
- [ ] Use existing code as much as possible
- [ ] Include only the code necessary for the component
- [ ] Affect as few other components as possible
- [ ] Use USWDS code style
- [ ] Use only USWDS design tokens, mixins, and functions
- [ ] Use the same design patterns to solve the same problems

### Accessible
- [ ] Add component-based tests to automated testing
- [ ] Pass automated CI accessibility review (aXe)
- [ ] Pass semi-automated accessibility review like [Accessibility Insights](https://accessibilityinsights.io/)
- [ ] Pass WCAG 2.1 review
- [ ] Use screen reader and keyboard accessible markup
- [ ] Make scrollable elements focusable for keyboard users
- [ ] Assure markup describes a logical structure/outline

### Resilient
- [ ] Use a mobile-first design methodology
- [ ] Stress-test with edge cases (and document these variants in the library)
- [ ] Outline contexts where this component might appear (and add these templates to the library)
- [ ] Perform critical tasks with low bandwidth and unreliable CSS load
- [ ] Perform critical tasks when JavaScript does not load
- [ ] Document and addresses any new package vulnerability
- [ ] Pass Snyk scan
- [ ] `npm audit`: Contain no Critical vulnerabilities 
- [ ] `npm audit`: Contain no High vulnerability standard dependencies
- [ ] Justify any High vulnerability dev dependencies
- [ ] Provide a print stylesheet
- [ ] Autoprefix with: `"> 2%", "Last 2 versions", "IE 11"`
- [ ] Test back to IE11 with a cross-platform testing tool
- [ ] Include functional unit tests

### Evidence-based
- [ ] Document internal or external developer usability test findings (and link to the documentation)
- [ ] Document internal or external end-user usability test findings (and link to the documentation)
- [ ] Collect links and references to any sources used to create this component in the documentation
- [ ] Perform landscape analysis of existing government examples of the component
- [ ] Compare component features with landscape to assure we're meeting expectations

### Documented
- [ ] Include a guidance page on the [`uswds-site`](https://github.com/uswds/uswds-site) linked to the new [`uswds`](https://github.com/uswds/uswds-site) work branch via `package.json`
- [ ] Include the following sections in site documentation:
  - [ ] Name
  - [ ] Description
  - [ ] Example
  - [ ] Component code
  - [ ] When to use
  - [ ] When to consider something else
  - [ ] Usability guidance
  - [ ] Accessibility guidance
  - [ ] Implementation guidance
  - [ ] When to consider something else
  - [ ] Resources
  - [ ] Package information
- [ ] Document any additions to USWDS settings on the [settings page](https://designsystem.digital.gov/documentation/settings/)
- [ ] Create a [component package](https://designsystem.digital.gov/components/) that allows Sass to import only that component and its dependencies. See [an example](https://github.com/uswds/uswds/blob/develop/src/stylesheets/packages/_usa-search.scss).
- [ ] Use plain language and explain any technical terms
- [ ] Document source code with comments
- [ ] Include a blog post that contextualizes the component work and explains what, why, and how of the component
- [ ] Content proofread with no typos or broken links

**Comment by maya** [comment]
Can this also address how breadcrumbs should be used with existing navigation components, specifically the sidebar navigation, as that component can also provide site hierarchy?

**Comment by thisisdano** [comment]
That's a good point. I think that even though breadcrumbs can provide some redundancy with existing nav, there's an opportunity — particularly on mobile — to foreground a bit of hierarchy, especially since our default components/layouts hide nav stuff either at the bottom of the page or within a menu.

**Comment by mejiaj** [comment]
>Autoprefix with: "> 2%", "Last 2 versions", "IE 11"

Do we add `not dead`?
