### ISSUE TITLE
Identifier Wireframes

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3565]
As a UX specialist, I want to create a well thought wireframe to solicit new component feedback from users so that I can better understand how to define requirements. feedback received will influence the prototype
As the USWDS core team, a fractal prototype will be developed and tested, draft guidance created.

https://github.com/uswds/uswds-team/issues/32

**Tasks to complete**
-	[x] Create [Wireframe](https://bixal.invisionapp.com/public/share/GPY9M9N2N7K)
-	[x] Create language to solicit community feedback
-	[x] Create supporting visuals/medium to solicit [community feedback ](https://drive.google.com/file/d/1E73sLPtcl7X4b2dLZ6MwBYMbEiREPvql/view)
-	[x] Compile and [review feedback](https://docs.google.com/spreadsheets/d/1XcLlqHQccyeek9IW6vxa20dWqVPY_PUEPRrGsgvuOgs/edit#gid=0)
-	[x] Incorporate feedback into response, update wireframe/prototype
- [x] Update [codepen ](https://codepen.io/mejiaj/live/ExPBrjO)
- [x] [Fractal prototype](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-component-anchor/components/detail/anchor.html), draft built in DS (@mejiaj )
- [x] Accessibility audit 8/26
- [x] Draft of [guidance page](https://docs.google.com/document/d/1Ec1D3o53WAEDYvnZ7aWqewlO6VAdeVEA361wATsdL-o/edit) (@katieekline )

**Acceptance criteria**
-	[x] Wireframe approved
-	[x] Feedback is solicited
-	[x] Feedback is captured, analyzed, incorporated into Prototype
-	[x] Prototype draft in DS
- [x] Accessibility audit compete and passed 
- [x] Draft of guidance page created

**Definition of Done**
• Meets acceptance criteria
• Cared Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by jAigret-Bix** [comment]
Files reviewed on 8.4:
desktop and mobile: https://bixal.invisionapp.com/share/GPY9M9N2N7K
footer variations: https://bixal.invisionapp.com/share/GPY9M9N2N7K#/427073995_Additional_Footer_Options
 
code pen here: 
Live view:
https://codepen.io/mejiaj/live/ExPBrjO
Editor view:
https://codepen.io/mejiaj/pen/ExPBrjO

**Comment by mejiaj** [comment]
[Anchor Prototype in fractal](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-component-anchor/components/detail/anchor.html)

**Comment by katieekline** [comment]
@thisisdano The [draft guidance page](https://docs.google.com/document/d/1Ec1D3o53WAEDYvnZ7aWqewlO6VAdeVEA361wATsdL-o/edit?usp=sharing) is ready for your review.

**Comment by jAigret-Bix** [comment]
Wireframe and initial prototype tasks are complete. Moving this to review for close out. @thisisdano
