### ISSUE TITLE
Security page: add hash // starter content

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3569]
Add a hash to the package to verify its authenticity.  
Starter Content is [here](https://docs.google.com/document/d/1pcKr-1RHgWqVL7g3iQLhBWbczRijcl6jIQJ8ZM3o6z0/edit?usp=sharing)

**Tasks to complete**
-	[x] Discover best practices for hash addition
- [x] Create starter content
[Draft content](https://docs.google.com/document/d/1pcKr-1RHgWqVL7g3iQLhBWbczRijcl6jIQJ8ZM3o6z0/edit?usp=sharing)
[PR](https://github.com/uswds/uswds-site/pull/1032)
[Preview page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-add-security-page/about/security-information/)
- [x] located `about`
-	[x] add hash to the package to verify it’s authenticity
-	[x] test 

**Definition of Done**
• Meets acceptance criteria
• Cared Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by mejiaj** [comment]
In researching this I've found:

Using this plugin to generate a hash that can be generated and compared to verify a directory hasn't been modified.
https://pypi.org/project/checksumdir/1.0.5/

gpg is an open source standard to generate a key users can check to verify integrity.
https://www.gnupg.org/gph/en/manual/x135.html
https://gnupg.org/download/integrity_check.html

**Comment by jAigret-Bix** [comment]
[Draft content](https://docs.google.com/document/d/1pcKr-1RHgWqVL7g3iQLhBWbczRijcl6jIQJ8ZM3o6z0/edit?usp=sharing) 
[PR](https://github.com/uswds/uswds-site/pull/1032)
[Preview page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-add-security-page/about/security-information/)

**Comment by jAigret-Bix** [comment]
@afeijoo  [Preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-add-security-page/about/security-information/) 
[PR link](https://github.com/uswds/uswds-site/pull/1032)

Ready for content review

**Comment by afeijoo** [comment]
@jAigret-Bix and @mejiaj Reviewed.

**Comment by jAigret-Bix** [comment]
JA 8/27: Waiting to publish documentation page until hash is secured and complete. Content has been reviewed, no requests for changes.

**Comment by mejiaj** [comment]
**Blocked**

I have a [jm-add-security-hash](https://github.com/uswds/uswds-site/tree/jm-add-security-hash) branch.  

But there seems to be an issue with getting the generated hash. Probably because the default API branch is `develop`? Blocked until we can figure this out or find a way around it.

**Comment by mejiaj** [comment]
Maybe [appendfile](https://nodejs.org/api/fs.html#fs_fs_appendfile_path_data_options_callback) can unblock now that the Security page is going to be in USWDS. [PR](https://github.com/uswds/uswds/pull/3609)

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds/pull/3609
