### ISSUE TITLE
Convert Nunjucks file to Twig file per component

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3600]
Convert to twig file per component:

- [x] Accordion
- [x] Alert
- [x] Banner
- [x] Breadcrumb
- [x] Button
- [x] Button groups
- [x] Card
- [x] Data visualizations
- [x] Footer
- [x] Form controls
- [x] Form templates
- [x] Graphic Lists
- [x] Grid
- [x] Header
- [x] Icons
- [x] Identifier
- [x] Search
- [x] Side navigation
- [x] Step indicator
- [x] Table
- [x] Tag
- [x] Tooltip
- [x] Typography

**Tasks per component**
- [x] Create component folder
- [x] Refactor Gulp Tasks
- [x] Add Browsersync and Pattern Lab tasks
- [x] Modify Package scripts
- [x] Test Gulp build and Gulp watch
- [x] Pull baseline into USWDS Site and test
- [x] Scaffold component (twig, yml, md, scss)
- [x] Refactor nunjucks file into twig file
- [x] Refactor yml file into Pattern Lab yml file
- [x] Create md file for component documentation
- [x] Modify scss file as needed to compile properly
- [x] Preview component in Pattern Lab
- [x] Create yml variants as needed
 
*Note: bear in mind, maybe look @ states and see if we can use templates as on output for unit tests

**DOD**
Component is considered done once it has been previewed in Pattern Lab, Tested from responsiveness and accessibility and functions as current component.

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds/pull/3804
