### ISSUE TITLE
Identifier front-end development // Release ready

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3601]
Anchor front-end development

Anchor component and guidance ready for 2.9.0 release. all tasks completed by 9/4. Release scheduled for 9/10.  

**Tasks to complete**
- [x] update fractal prototype v2 feedback
- [x] finalize [prototype](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-component-anchor/components/detail/identifier--default.html) w client and team
- [x] user testing as needed (N/A)
- [x] create and finalize [guidance](https://docs.google.com/document/d/1Ec1D3o53WAEDYvnZ7aWqewlO6VAdeVEA361wATsdL-o/edit)
- [x] create and finalize [release notes](https://docs.google.com/document/d/1EwumkSvjz8hKwSryD0LBV7fFcU-oBUtdRUCeL83P598/edit) (@allie-shaw )
- [X] final accessibility check (9/4)
- [x] update Sketch and XD files 
- [x] Update research plan and feature brief
- [x] create [component page](USWDS - Documentation: Create Identifier component page. #1043)
- [x] check settings and variants
- [x] add code to component page
- [x] QA and review PR
- [x] Add description of feature specifications to feature brief

**DOD**
- [x] All tasks complete
- [x] CARED component evaluation Framework: Clear, Accessible, Resilient, Evidence-based, Documented

**Comment by thisisdano** [comment]
Released in USWDS 2.9.0: https://github.com/uswds/uswds/releases/tag/v2.9.0
