### ISSUE TITLE
Interview ID 0017

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3637]
See [Accelerator Interviews spreadsheet](https://docs.google.com/spreadsheets/d/10DQtLPs9YcoyGlK-8brg9qFYZasmBgFppCtQZRuSweQ/edit)

**Task checklist** per the Interview Guide. There are currently two versions of the Interview Guide: [one in the GSA Google Drive space](https://docs.google.com/document/d/1Do9Yq3P6G1eFc6cYBVtq3PURH-DtpPrpBxRvMCILRvk/edit), and a [temporary version in the Flexion Google Drive space](https://docs.google.com/document/d/1CixY91rx0XXWJeJJcI66IoiEdK6TMmosyN4qBx_to6k/edit).

**Prep**
- [x] Create GitHub issue
- [x] Identify interview subjects:
    - Do not add interview subject names to GitHub issues. Protect their identity by using anonymous pseudonyms.
- [x] Send intro email to interview subjects
    - Use [Accelerator interviewee intro](https://docs.google.com/document/d/1iP6w-IAVXevj36D6tSrQtstnsXDYVh3nNajIIAD1ptU/edit)
    - Copy Ammie and Dan
- [x] Identify interviewer & note-taker:
Interviewer: Ben Judy
Note-taker: Kim Schulke
- [x] Schedule in Google Calendar
    - add to team calendar TTS-USWDS-Accelerator
    - Subject template: `[Firstname Lastname] - US Web Design System Accelerator chat`
- [x] Schedule 15-20 minutes debrief after each interview
- [x] Create notes doc w/ prioritized list of questions
[Notes doc here](https://docs.google.com/document/d/15vkABIME-cm2qwNCes0lT9rb_PvHpgc9Nek6zfzHGe0/edit)
- [x] Answer “Questions to answer internally before the interview” in notes doc

**During interview**
- [x] Ask for permission to record
- [x] Capture raw notes

**Post-interview**
- [x] Capture insights in Synthesis spreadsheet
- [x] Update Accelerator Interviewees spreadsheet
- [x] Archive recording

**Comment by Ben-Judy-Flexion** [comment]
I sent a meeting invite to Carla, scheduled for 2:00pm CDT on Friday 9/25.

**Comment by ardenk** [comment]
Notetaking guide: https://docs.google.com/document/d/15vkABIME-cm2qwNCes0lT9rb_PvHpgc9Nek6zfzHGe0/edit#

**Comment by Ben-Judy-Flexion** [comment]
Here are my top takeaways from this interview. We can copy these to a wiki or synthesis doc or report, or wherever we end up publishing research summaries.

- **USWDS is difficult to use for agencies who have invested in a web application framework to host their web sites.**
The [AFPIMS](https://www.dma.mil/Services/DOD-Public-Web/) (American Forces Public Information Management System) CMS runs on [DNN](https://en.wikipedia.org/wiki/DNN_(software)). It can be described as "GoDaddy for government" or "Wordpress for the military." Some aspects of USWDS code such as naming conventions can be adopted within this environment, but people who stand up sites within AFPIMS see USWDS as a general guide, not a code base they can easily implement.
- **Some web developers think USWDS doesn't provide branding and configuration options they need.**
"Very few of our customers would be okay with a site that looks like what the USWDS provides. They want their branding." This may be more of a perception issue than a real problem, as USWDS allows for significant configuration and look-and-feel customization.
- **Special content components that can be quickly turned on are important for emergency response.**
AFPIMS provides a "Hot Info" module that can function as an alert banner at the top of a web page. It has proven to be a popular module for DoD sites to draw attention to COVID-19 related information.
- **DoD Public Affairs personnel don't engage in a lot of information sharing or community activities related to web design and development.**
There are closed Facebook groups for the Public Affairs community, but discussion are typically about how to get a commander's message out, not how to add components to a web site or how to improve accessibility, etc. The AFPIMS Product Manager used to send an email newsletter but got feedback that Public Affairs personnel were too busy to read it. For many people who maintain and publish to DoD web sites, this is a part-time responsibility, not a full-time job.
There may be an opportunity for USWDS to serve as an easy place for people to join a community of web publishers on their own terms.
