### ISSUE TITLE
USWDS-Accordion: add "expand all'' functionality

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3654]
Accordion: add "expand all'' functionality

#3435 (original issue)
#3446 (Prototype)

**Tasks to complete**

- [ ] Add `expand all` and `collapse all` functionality 
- [ ] Is this a retrofit or a new feature?
- [ ] Define and text printing expectations, what should users see (or not) when printing
- [ ] Update guidance, make clear how collapsing affects searchability and printing

**Comment by bruce-usab** [comment]
Access Board would is pleased to be an early implementer, test, and provide feedback.

Our first page where I have already been asked to incorporate an accordion is here:
https://beta.access-board.gov/about/policy/privacy.html

Repo page is here:
https://github.com/atbcb/usab-uswds/blob/master/_pages/p-privacy.md

Pinging @RSD-accessboard

**Comment by gillick** [comment]
> Accordion: add "expand all'' functionality
> 
> #3435 (original issue)
> #3446 (prototype)
> 
> **Tasks to complete**
> 
> * [ ]  Add `expand all` and `collapse all` functionality
> * [ ]  Is this a retrofit or a new feature?
> * [ ]  explore accessibility issues and testing
> * [ ]  Define text printing expectations, what should users see (or not) when printing
> * [ ]  Update guidance, make clear how collapsing affects searchability and printing

Quick reminder: This feature request has its roots in making on-page search (ctrl-f) work on pages with accordions. Expand-all is nice, but the real usability is in making on-page search work.

**Comment by jAigret-Bix** [comment]
Accessibility meeting 10.29. James will send out testing page week of 11.2

**Comment by jAigret-Bix** [comment]
accessibility [testing link](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-accordion-all/components/preview/layout--content.html) sent 11.4

**Comment by jAigret-Bix** [comment]
@thisisdano @mejiaj tested and passed compliance. Multi-selection and state tracking are possible future enhancements with more complicated code.

**Comment by mejiaj** [comment]
@thisisdano one of the concerns with this new feature was regarding multi-selection. If a user on a screen reader jumped to an accordion item and expanded 1 or more items (from default state). Then went up to controls — there would be no way to know what is the current state of accordion.

@gillick I'm not aware of anything that can be done to make this more searchable, unless you show the expanded state by default. I think there's any way around that unless you _don't_ use accordion. If you do know of any examples, please share

**Comment by jAigret-Bix** [comment]
@mejiaj  a few notes from IE11 testing. Linked into issue above.

**Comment by mejiaj** [comment]
@jAigret-Bix we should confirm zoom issue and locked padlock with @thisisdano and create issues if confirmed.

**Comment by bruce-usab** [comment]
Pinging @rsd-accessboard and @kengdoj to ask if we can incorporated the expand all function to [this page of ours](https://www.access-board.gov/504-contacts/).

**Comment by jAigret-Bix** [comment]
blocked by #4040

**Comment by bruce-usab** [comment]
Sorry for not spotting this earlier, and it may OBE.


@mejiaj wrote:
> I'm not aware of anything that can be done to make this more searchable, unless you show the expanded state by default.

My own frequent experience is that Google and Search.gov will surface a page -- so I know there is a hit for what I am looking for!  But there could be many accordions for me to digging through (one-by-one) to find it.

Here is an example I struggled with earlier today:
https://www.google.com/search?q=%22congressional+budget+justifications%22+site:digital.gov

**Comment by arkjoseph** [comment]
What happened to this enhancement?

**Comment by mejiaj** [comment]
We lacked user research to provide adequate guidance for this feature. 

We should consider pushing this feature as experimental as part of #6379.

**Comment by gillick** [comment]
> What happened to this enhancement? 

IIRC, the expand/collapse feature was something of a kludge to make ctrl-f "find" work, when all that was really needed was hidden until found or a better accordion. The expand/collapse feature also didn't solve for the second issue: SERP text links being not-quite compatible with the existing accordions.

**Comment by annepetersen** [comment]
USWDS is currently understaffed, so I'm closing items that aren’t as high on the priority list right now, including this one, unfortunately.

**Comment by caseywatts** [comment]
As of a month or two ago, there is an **implementation** of the USWDS accordion component that has a "toggle all" feature!

In the OGDS repo:
https://github.com/open-government-design-system/ogds-elements

Accordion Toggle:
https://ogds-elements.jbhutch01.workers.dev/?path=/docs/components-accordion-toggle--docs
