### ISSUE TITLE
Create login/signup flow pattern

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3656]
## Milestones

DESIGN ASSETS
- [x] 10% - Collect and analyze examples, draft research insights, draft list of features
- [x] 20% - Low-fi design review
- [x] 40% - Template designs approved by Dan
---------design closeout---------
- [ ] 60% - Add template(s) to Sketch and XD
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews) - in [Mural](https://app.mural.co/t/flexion6734/m/flexion6734/1600718591376/0b4f8d81512a19034ca5fc1f1759c8913c20b359)
- [x] 20% - Draft guidance review #1 (minimum 2 bullets each section)
- [x] 40% - Get SME feedback on draft guidance **[In Progress]**
- [x] 60% - Draft guidance in sections **- Due Tuesday 11/10**
- [x] 70% - Internal content review (Natalie's) **- Due Wednesday 11/11**
- [x] 80% - Draft guidance review #3 (w/ Dan) **- blocked: waiting for Login.gov**
- [ ] 100% - PR approved by Dan

CODE
- [x] 5% - Confirm whether or not we're building templates, and which ones **[Confirmed]**

_All three templates ready for review **Due Tuesday 11/10**_
- [x] 10% - Code review #1 (Federalist preview) - interaction design focus - 
- [x] 20% - Code review #2 (Federalist preview) - visual design focus
        _*We have access to crossbrowsertesting.com and AWS Workspace with NVDA for a11y testing_
- [x] 40% - Get community feedback or conduct tests with users, round 1
- [x] 60% - Code review #3 (Federalist preview) - accessibility focus
- [x] 65% - PR to Dan

- [x] 80% - Get community feedback or conduct tests with users, round 2 **- Due Thursday 11/12**
- [ ] 100% - PR approved by Dan

**Comment by debjudy** [comment]
related issue #3432

**Comment by ardenk** [comment]
@jaredcunha Please add the following:

Label: "Accelerator-Joi"
Assignees: Jared (YOU!)
Checklist:
- [ ] Landscape Analysis
- [ ] USWDS component download from Ben
- [ ] Sketch/Design in Figma (First Draft)
- [ ] Identify users for testing
- [ ] Usability Testing
- [ ] Client Review
- [ ] Finalize Design/Convert to Sketch
- [ ] Documentation

**Comment by ardenk** [comment]
@jaredcunha can you update the name to reflect that this is a "pattern" rather than a "component" ?

**Comment by ardenk** [comment]
First design draft of login page.
![login-desktop-10022020](https://user-images.githubusercontent.com/2301104/94930452-5289ec00-04be-11eb-9261-45573157ac16.jpg)

**Comment by ardenk** [comment]
Work session with Jared, we're thinking about reducing the cognitive load, and placing the crisis banner in a "global" location as this will likely be shown on other pages, too. Researching placement of create account link.

![image](https://user-images.githubusercontent.com/2301104/95228278-0b219980-07f7-11eb-99d9-2c4f6aea7e07.png)

**Comment by ardenk** [comment]
Login page user flows with @jaredcunha 
![image](https://user-images.githubusercontent.com/2301104/95230294-9ac84780-07f9-11eb-8346-f14179e1b771.png)

**Comment by debjudy** [comment]
@ardenk @jaredcunha Are you ready to share out what you have thus far during review on 10/16?

**Comment by jaredcunha** [comment]
@debjudy It's not complete, but we have a basic direction where we want to go with it and I've started drafting a Google Doc. But I think it'd be really helpful to get a gut-check on that direction.

**Comment by ardenk** [comment]
## Base template designs

### Navigation header

**Sign in locally**
![header-sign-in-local](https://user-images.githubusercontent.com/2301104/97338721-fe3a1800-1881-11eb-9002-616ad31ff9e9.jpg)
 - separate sign in / create account buttons

**Sign in using third party account**
![header-sign-in-third-party](https://user-images.githubusercontent.com/2301104/97338725-ff6b4500-1881-11eb-8bfd-92c5d7c17903.jpg)
 - single button using "sign in" icon
 - this takes user off site for third party sign in

**Signed in state**
![header-sign-out](https://user-images.githubusercontent.com/2301104/97338729-009c7200-1882-11eb-860c-c9c82e8657b4.jpg)
 - indicate who is signed in
 - option to sign out
 - larger sites may customize this to include a drop down to access account settings, etc

### Local authentication

**Create account**
![create-account-local](https://user-images.githubusercontent.com/2301104/97338495-be733080-1881-11eb-9547-ce7c50be0126.jpg)

**Sign in**
![sign-in-local-federal-employee-option](https://user-images.githubusercontent.com/2301104/97338517-c337e480-1881-11eb-95be-2723dea0d40b.jpg)
![sign-in-local-mobile](https://user-images.githubusercontent.com/2301104/97338519-c337e480-1881-11eb-8bdf-b948c27db02f.jpg)
![sign-in-local](https://user-images.githubusercontent.com/2301104/97338520-c3d07b00-1881-11eb-9470-594bffbc496a.jpg)

### Sign in with legacy options

![sign-in-legacy-mobile](https://user-images.githubusercontent.com/2301104/97338507-c16e2100-1881-11eb-8882-9cb67162f1f2.jpg)
![sign-in-legacy](https://user-images.githubusercontent.com/2301104/97338513-c29f4e00-1881-11eb-94e9-57556d46b6a0.jpg)

_Note that a single third party sign in page is not shown because the sign in link in the header goes directly off site. However, if an agency wants a landing page they can use "Sign in with legacy options" with only one primary button._

**Comment by ardenk** [comment]
Approved to make the following templates:
 - Create account
 - Sign in
 - Sing in with legacy options

From Slack:
https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1603910348213100?thread_ts=1603820313.192100&cid=C01ATNBSTTP

cc @jaredcunha

**Comment by ardenk** [comment]
Checked off:
- [x] 10% - Summarize insights from research (desk + interviews) - in Mural
with a 👍🏼 from team Judy @Ben-Judy-Flexion and @debjudy

**Comment by ardenk** [comment]
Updated due dates ^^

**Comment by ardenk** [comment]
Received 👍 on guidance draft from @Ben-Judy-Flexion and @debjudy, delivered to Natalie for content review. Note, we're still missing a section on the required standards, which should be provided by the Login.gov team. cc @jaredcunha

**Comment by ardenk** [comment]
User stories for this component:
![image](https://user-images.githubusercontent.com/2301104/98971711-ceda0b00-2511-11eb-82a6-d2517bb00587.png)
![image](https://user-images.githubusercontent.com/2301104/98971736-d8637300-2511-11eb-9309-b47b17d58e73.png)

And relevant interview quotes
**Theme: common page types help overall usability of government websites**
 - I’d love to see more common components, pages or types of content or templates like login pages.
 - Bringing more standardization to login pages prevents people from having to relearn every time.
 - The more we can use the design system to provide standardized ways of building common pieces of information or types of pages will help improve how the federal web functions.
**Theme: encourage adoption by showing agencies how it works**
 - Whatever types of transactional flows are common: authentication etc. Reference designs to see all the parts composed.
 - An example is ecommerce flows, or whatever type of transactional flows are common like authentication and managing people and whatever, having reference designs to see all the parts composed will go a long way to help them understand.
**Theme: leverage shared services**
 - A  lot of agencies don’t want to maintain their own login systems” State and local governments too.
 - A lot of agencies are going to start using login.gov” i push that to be the guidance.
 - US web design system can say use login.gov.
 - [Agency], login is changing. They have something called SBA connect, sort of a middle way. VA has accessVA. Look at that.
 - There’s a lot that comes to authentication and identity that agencies need.

**Comment by jaredcunha** [comment]
There could be some slight updates to the templates based on whatever resolution is reached in this conversation: https://github.com/uswds/uswds/issues/3691
