### ISSUE TITLE
Interview ID 0033

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3659]
See [Accelerator Interviews spreadsheet](https://docs.google.com/spreadsheets/d/10DQtLPs9YcoyGlK-8brg9qFYZasmBgFppCtQZRuSweQ/edit)

**Task checklist**
The following task checklist corresponds with the Interview Guide. There are currently two versions of the Interview Guide: [one in the GSA Google Drive space](https://docs.google.com/document/d/1Do9Yq3P6G1eFc6cYBVtq3PURH-DtpPrpBxRvMCILRvk/edit), and a [temporary version in the Flexion Google Drive space](https://docs.google.com/document/d/1CixY91rx0XXWJeJJcI66IoiEdK6TMmosyN4qBx_to6k/edit).

**Prep**
- [x] Create GitHub issue
- [x] Identify interview subjects:
    - Do not add interview subject names to GitHub issues. Protect their identity by using anonymous pseudonyms.
- [x] Send intro email to interview subjects
    - Use [Accelerator interviewee intro](https://docs.google.com/document/d/1iP6w-IAVXevj36D6tSrQtstnsXDYVh3nNajIIAD1ptU/edit)
    - Copy Ammie and Dan
- [x] Identify interviewer & note-taker:
Interviewer: Kim
Note-taker: Deb
- [x] Schedule in Google Calendar
    - add to team calendar TTS-USWDS-Accelerator
    - Subject template: `[Firstname Lastname] - US Web Design System Accelerator chat`
- [x] Schedule 15-20 minutes debrief after each interview
- [x] Create notes doc w/ prioritized list of questions
[Notes doc here](https://docs.google.com/document/d/1xjCK_TSW_XPKVXyZ-YmVt8P1ZUgXxj7ndhj_z_eXqrU/edit)
- [x] Answer “Questions to answer internally before the interview” in notes doc

**During interview**
- [x] Ask for permission to record
- [x] Capture raw notes

**Post-interview**
- [x] Capture insights in Synthesis Mural
- [x] Update Accelerator Interviewees spreadsheet
- [x] Archive recording

**Comment by uxforgood** [comment]
Email sent 9/28
