### ISSUE TITLE
Interview ID 0023

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3660]
See [Accelerator Interviews spreadsheet](https://docs.google.com/spreadsheets/d/10DQtLPs9YcoyGlK-8brg9qFYZasmBgFppCtQZRuSweQ/edit)

**Task checklist**
The following task checklist corresponds with the Interview Guide. There are currently two versions of the Interview Guide: [one in the GSA Google Drive space](https://docs.google.com/document/d/1Do9Yq3P6G1eFc6cYBVtq3PURH-DtpPrpBxRvMCILRvk/edit), and a [temporary version in the Flexion Google Drive space](https://docs.google.com/document/d/1CixY91rx0XXWJeJJcI66IoiEdK6TMmosyN4qBx_to6k/edit).

**Prep**
- [x] Create GitHub issue
- [x] Identify interview subjects:
    - Do not add interview subject names to GitHub issues. Protect their identity by using anonymous pseudonyms.
- [x] Send intro email to interview subjects
    - Use [Accelerator interviewee intro](https://docs.google.com/document/d/1iP6w-IAVXevj36D6tSrQtstnsXDYVh3nNajIIAD1ptU/edit)
    - Copy Ammie and Dan
- [x] Identify interviewer & note-taker:
Interviewer: @uxforgood 
Note-taker: Arden
- [x] Schedule in Google Calendar
    - add to team calendar TTS-USWDS-Accelerator
    - Subject template: `[Firstname Lastname] - US Web Design System Accelerator chat`
- [x] Schedule 15-20 minutes debrief after each interview
- [x] Create notes doc w/ prioritized list of questions
[Notes doc here](https://docs.google.com/document/d/15vkABIME-cm2qwNCes0lT9rb_PvHpgc9Nek6zfzHGe0/edit)
- [x] Answer “Questions to answer internally before the interview” in notes doc

**During interview**
- [x] Ask for permission to record
- [x] Capture raw notes

**Post-interview**
- [x] Clean up notes and share insights with team
- [x] Capture insights in Interview Synthesis Mural
- [x] Update Accelerator Interviewees spreadsheet
- [x] Move recording to Research Interview Recordings folder

**Comment by uxforgood** [comment]
Scheduling email sent 9/28

**Comment by ardenk** [comment]
@uxforgood can you update **Post-interview**

- [ ] Clean up notes and share insights with team
- [ ] Capture key insights in Interview Synthesis Mural

^^ Mural replaces spreadsheet hete

**Comment by uxforgood** [comment]
@ardenk Updated

**Comment by debjudy** [comment]
@ardenk @Ben-Judy-Flexion Okay to close this issue?

**Comment by Ben-Judy-Flexion** [comment]
@debjudy I wasn't in this interview, and it's assigned to Natalie so she should close it out. (Although it is confusing to know who is involved, because my name is all over this Issue as a commenter. All I did was create the Issue and assign it, though.)

**Comment by debjudy** [comment]
@Ben-Judy-Flexion my mistake I should have noticed that
@uxforgood okay to close?
