### ISSUE TITLE
Interview ID 0031, 0032

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3663]
See [Accelerator Interviews spreadsheet](https://docs.google.com/spreadsheets/d/10DQtLPs9YcoyGlK-8brg9qFYZasmBgFppCtQZRuSweQ/edit)

**Task checklist**
The following task checklist corresponds with the Interview Guide. There are currently two versions of the Interview Guide: [one in the GSA Google Drive space](https://docs.google.com/document/d/1Do9Yq3P6G1eFc6cYBVtq3PURH-DtpPrpBxRvMCILRvk/edit), and a [temporary version in the Flexion Google Drive space](https://docs.google.com/document/d/1CixY91rx0XXWJeJJcI66IoiEdK6TMmosyN4qBx_to6k/edit).

**Prep**
- [x] Create GitHub issue
- [x] Identify interview subjects:
    - Do not add interview subject names to GitHub issues. Protect their identity by using anonymous pseudonyms.
- [x] Send intro email to interview subjects
    - Use [Accelerator interviewee intro](https://docs.google.com/document/d/1iP6w-IAVXevj36D6tSrQtstnsXDYVh3nNajIIAD1ptU/edit)
    - Copy Ammie and Dan
- [x] Identify interviewer & note-taker:
Interviewer: Ben Judy
Note-taker: Ben Judy
- [x] Schedule in Google Calendar
    - add to team calendar TTS-USWDS-Accelerator
    - Subject template: `[Firstname Lastname] - US Web Design System Accelerator chat`
- [x] ~~Schedule 15-20 minutes debrief after each interview~~
- [x] Create notes doc w/ prioritized list of questions
[Notes doc here](https://docs.google.com/document/d/15vkABIME-cm2qwNCes0lT9rb_PvHpgc9Nek6zfzHGe0/edit)
- [x] ~~Answer “Questions to answer internally before the interview” in notes doc~~

**During interview**
- [x] Ask for permission to record
- [x] Capture raw notes

**Post-interview**
- [x] Capture insights in [Synthesis Mural](https://app.mural.co/t/flexion6734/m/flexion6734/1601055757627/56683bc207068e5059bde3b07d8d37a2964f7d93)
- [x] Update [Accelerator Interviewees](https://docs.google.com/spreadsheets/d/10DQtLPs9YcoyGlK-8brg9qFYZasmBgFppCtQZRuSweQ/edit#gid=0) spreadsheet
- [x] Archive recording ([here](https://app.mural.co/t/flexion6734/m/flexion6734/1601055757627/56683bc207068e5059bde3b07d8d37a2964f7d93))

**Comment by Ben-Judy-Flexion** [comment]
Ammie sent follow-up on 10/2
Ben sent email on 9/25 requesting available time slots
Jacob sent intro on 9/24

**Comment by debjudy** [comment]
@Ben-Judy-Flexion Ammie mentioned that she saw a response from this interviewee and that it will behoove us to jump on his calendar.

**Comment by Ben-Judy-Flexion** [comment]
Interview scheduled for Monday 10/19

**Comment by Ben-Judy-Flexion** [comment]
Closed the [Issue for interview with 0031](https://github.com/uswds/uswds/issues/3664).
This Issue will be for combined interview with 0031 and 0032.
