### ISSUE TITLE
Interview ID 0006, 0007, 0008, 0057, 0058, 0059, 0060, 0061 (group interview)

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3668]
See [Accelerator Interviews spreadsheet](https://docs.google.com/spreadsheets/d/10DQtLPs9YcoyGlK-8brg9qFYZasmBgFppCtQZRuSweQ/edit)

**Task checklist**
The following task checklist corresponds with the Interview Guide. There are currently two versions of the Interview Guide: [one in the GSA Google Drive space](https://docs.google.com/document/d/1Do9Yq3P6G1eFc6cYBVtq3PURH-DtpPrpBxRvMCILRvk/edit), and a [temporary version in the Flexion Google Drive space](https://docs.google.com/document/d/1CixY91rx0XXWJeJJcI66IoiEdK6TMmosyN4qBx_to6k/edit).

**Prep**
- [x] Create GitHub issue
- [x] Identify interview subjects:
    - Do not add interview subject names to GitHub issues. Protect their identity by using anonymous pseudonyms.
- [x] Send intro email to interview subjects
    - Use [Accelerator interviewee intro](https://docs.google.com/document/d/1iP6w-IAVXevj36D6tSrQtstnsXDYVh3nNajIIAD1ptU/edit)
    - Copy Ammie and Dan
- [x] Identify interviewer & note-taker:
Interviewer: Ben
Note-taker: Kim and Joi
- [x] Schedule in Google Calendar
    - add to team calendar TTS-USWDS-Accelerator
    - Subject template: `[Firstname Lastname] - US Web Design System Accelerator chat`
- [x] Schedule 15-20 minutes debrief after each interview
- [x] Create notes doc w/ prioritized list of questions
[Notes doc here](https://docs.google.com/document/d/1JTEMiJ2k0CCqHAWt1uJh8Ao8h_6pqKhmQeP-bfz6hRo/edit#)
- [x] Answer “Questions to answer internally before the interview” in notes doc

**During interview**
- [x] Ask for permission to record
- [x] Capture raw notes

**Post-interview**
- [x] Capture insights in [Mural](https://app.mural.co/t/flexion6734/m/flexion6734/1601055757627/56683bc207068e5059bde3b07d8d37a2964f7d93)
- [x] Update [Accelerator Interviewees spreadsheet](https://docs.google.com/spreadsheets/d/10DQtLPs9YcoyGlK-8brg9qFYZasmBgFppCtQZRuSweQ/edit)
- [x] Archive [recording](https://drive.google.com/drive/u/4/folders/1jmhOubChJvHe5PbIVvnGg8-lmgyIIFct)

**Comment by JoiCUX** [comment]
@Ben-Judy-Flexion here is the [notes link](https://docs.google.com/document/d/1JTEMiJ2k0CCqHAWt1uJh8Ao8h_6pqKhmQeP-bfz6hRo/edit?usp=sharing)
