### ISSUE TITLE
Create Collection component

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3676]
## Milestones

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback - on [Mural board](https://app.mural.co/t/flexion6734/m/flexion6734/1600718591376/0b4f8d81512a19034ca5fc1f1759c8913c20b359) - done Mon 11/2
- [x] 20% - Draft user story & clarify the problem(s) / user needs - on [Mural board](https://app.mural.co/t/flexion6734/m/flexion6734/1600718591376/0b4f8d81512a19034ca5fc1f1759c8913c20b359) - done Tue 11/3
- [x] 30% - Low-fi design review - done Tue 11/3
- [x] 40% - Get community feedback on initial, Hi-fi designs - done Tue 11/17
- [ ] 50% - Hi-fi Sketch assets review **- due Thu 12/3**
- [ ] 60% - Hi-fi Adobe XD assets review **- due Thu 12/3**
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files **- due Fri 12/4**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews) - done Mon 11/2
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) - done Thu 11/12
- [x] 40% - Get community feedback on draft guidance - done Tue 11/17
- [x] 50% - Draft guidance review no. 2 (accessibility focus) - done Tue 12/1
- [x] 60% - Draft guidance review no. 3 (w/ Dan) - done Tue 12/1
- [x] 80% - Add component to research report and slide deck **- due Thu 12/3**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

CODE
- [x] 10% - Code review no. 1 ([Federalist preview](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3676-news-feed-prototype/components/detail/featured-content.html)) - interaction design focus - done Tue 11/10
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus - done Fri 11/13
- [x] 40% - Get community feedback or conduct tests with users, round 1 - done Wed 11/18
- [x] 60% - Code review no. 3 (Federalist preview) - accessibility focus **- due Thu 12/3**
- [x] 80% - Get community feedback or conduct tests with users, round 2 **- due Thu 12/3**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

**Comment by JoiCUX** [comment]
@wbyoko I will be the UX researcher assigned to this component.  We should sync tomorrow.

**Comment by JoiCUX** [comment]
**@Ben-Judy-Flexion  Please add the following:**

1. Label: "Accelerator-Joi" 
2. Checklist: 

- [ ] Landscape Analysis

- [ ] USWDS component download from Ben

- [ ] Sketch/Design in Figma

- [ ] Identify users for testing

- [ ] Usability Testing 

- [ ] Client Review

- [ ] Finalize Design/Convert to Sketch

- [ ] Documentation

**Comment by Ben-Judy-Flexion** [comment]
I added a space for the New Feed component to our [Mural board](https://app.mural.co/t/flexion6734/m/flexion6734/1600718591376/0b4f8d81512a19034ca5fc1f1759c8913c20b359).
Use this to dump "stuff" (screenshots, questions, ideas, sketches, guidance, links) related to News Feed.

**Comment by ardenk** [comment]
Ammie mentioned that this could be called "featured content" per: https://digital.gov/resources/coronavirus-covid19-guidance-for-us-government/

**Comment by Ben-Judy-Flexion** [comment]
[Discussed](https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1604423056269400) `Draft user story & clarify the problem(s) / user needs` and got approval from @sknep and @debjudy. User stories are in the [Mural board](https://app.mural.co/t/flexion6734/m/flexion6734/1600718591376/0b4f8d81512a19034ca5fc1f1759c8913c20b359). Screenshot is also attached here.
Still plenty of opportunity to iterate and get input from others on the team, but I'm marking this milestone done.
![image](https://user-images.githubusercontent.com/56978395/98040456-edd7ef00-1de5-11eb-861b-ed8f4787ef7f.png)

**Comment by Ben-Judy-Flexion** [comment]
[Got a thumbs-up](https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1604502308312300) from @uxforgood and @sknep on this Design milestone: `30% - Low-fi design review`.

**Comment by Ben-Judy-Flexion** [comment]
William [posted](https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1605046801391700) a request for thumbs-up on Code: `10% - Code review no. 1 (Federalist preview) - interaction design focus`. Got one thumbs-up from @uxforgood and good question about clickable elements from @sknep which we will consider. I'm marking this milestone done.

**Comment by Ben-Judy-Flexion** [comment]
[Requested a thumbs-up](https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1605199495409300) from two team members on Guidance: `20% - Draft guidance review no. 1 (minimum 2 bullets each section)`.

**Comment by Ben-Judy-Flexion** [comment]
Renamed ~~Featured Content~~ to Preview List
