### ISSUE TITLE
Create Site Alert component (fka Violator Banner, Emergency Alert Banner)

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3679]
## Milestones

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback - done Mon 11/2
- [x] 20% - Draft user story & clarify the problem(s) / user needs - done Mon 11/9
- [x] 30% - Low-fi design review - done Mon 11/9
- [x] 40% - Get community feedback on initial, Hi-fi designs - done Fri 11/13
- [ ] 50% - Hi-fi Sketch assets review **- due Thu 12/3**
- [ ] 60% - Hi-fi Adobe XD assets review **- due Thu 12/3**
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files **- due Fri 12/4**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews) - done Fri 10/30
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) - done Fri 10/30
- [x] 40% - Get community feedback on draft guidance **- due Tue 11/17**
- [x] 50% - Draft guidance review no. 2 (accessibility focus) - done Tue 12/1
- [x] 60% - Draft guidance review no. 3 (w/ Dan) - done Tue 12/1
- [ ] 80% - Add component to research report and slide deck **- due Thu 12/3**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

CODE
- [x] 10% - Code review no. 1 ([Federalist preview](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3679-banner-violator-prototype/components/detail/site-alert--emergency.html)) - interaction design focus **- due Tue 11/10**
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus **- due Fri 11/13**
- [x] 40% - Get community feedback or conduct tests with users, round 1 **- due Wed 11/18**
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus **- due Thu 12/3**
- [ ] 80% - Get community feedback or conduct tests with users, round 2 **- due Thu 12/3**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

**Comment by debjudy** [comment]
Renamed component to "Emergency Alert" from "Banner-style violator".

**Comment by Ben-Judy-Flexion** [comment]
[Got a thumbs-up](https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1604059153238700) from @jonadecker and @ardenk on this Guidance milestone: `20% - Draft guidance review no. 1`

**Comment by Ben-Judy-Flexion** [comment]
[Posted](https://gsa-tts.slack.com/archives/C01ATNBSTTP/p1604946658361500) these milestones to Slack, requesting a thumbs-up from two team members:
```
20% - Draft user story & clarify the problem(s) / user needs
30% - Low-fi design review
```

**Comment by afeld** [comment]
Another use case: alerting users they have reached a staging site.

**Comment by dawnpm** [comment]
Could this also be used for flagging Archived content?
