### ISSUE TITLE
Update required links guidance

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3744]
**Description:** Update the [Required Web Content and Links page on digital.gov](https://digital.gov/resources/required-web-content-and-links/) to incorporate research and guidance in [Identifier](https://designsystem.digital.gov/components/identifier/) component.

**Tasks**
- [ ] Confirm PL link requirements (see [M-11-15](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2011/m11-15.pdf) and section 16.D.5 in [M-17-06](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf))
- [ ] Add VDP requirements (see [BOD-20-01](https://cyber.dhs.gov/bod/20-01/#implementation-guide))
- [ ] Draft [updated guidance](https://docs.google.com/document/d/1Yas7s92GRTbs46yvfpeiruhgm0GU22LqU9N9Fgu9rUE/edit?ts=5fa5c554) for Required Web Content and Links
- [ ] Ask for policy review and incorporate feedback
- [ ] Submit PR to publish updates on Digital.gov
- [ ] Draft email and other comms to share the updated guidance
- [ ] Send email to web managers community and other stakeholders

**DOD**
- [ ] All tasks are complete

**Other**
["Core Components"](https://docs.google.com/document/d/1ySdXCiQ09K-IcSDOCCF4SrgWKE_U8dba4PJ6IbFJt_w/edit#) draft content and comms plan https://github.com/uswds/uswds/issues/4021

**Comment by katieekline** [comment]
@afeijoo The suggested revisions to this [page](https://docs.google.com/document/d/1Yas7s92GRTbs46yvfpeiruhgm0GU22LqU9N9Fgu9rUE/edit?usp=sharing) are ready for your review.

**Comment by thisisdano** [comment]
Is this done?

**Comment by afeijoo** [comment]
No, I moved it back to `in progress`.

**Comment by thisisdano** [comment]
What still needs to be done here?

**Comment by afeijoo** [comment]
I updated the task list and DOD above.
