### ISSUE TITLE
Check and update Sketch assets

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3752]
Check and update Sketch assets for step indicator and time picker

**Tasks to Complete**

- [x] locate sketch files for step indicator and time picker 
- [x] edit/create as needed
- [x]  add to master file
 
Delivery files
[Slack](https://gsa-tts.slack.com/archives/C050HRGN7/p1602866834134500?thread_ts=1602679791.106000&cid=C050HRGN7)
https://gsa-tts.slack.com/files/U017VJU2AHF/F01CKC5HPV4/uswds-project.sketch
https://gsa-tts.slack.com/files/U017VJU2AHF/F01CSABM519/uswds-components-as.xd

**Comment by allie-shaw** [comment]
Compared Sketch file against "components.designsystem.digital.gov"
- Navigation – Skip Navigation?
- Graphic list – Do we need to create a Sketch version?
- Hero – Do we need to create a Sketch version?
- Utilities – Do we need an Aspect Ratio Version in Sketch?
@thisisdano @jAigret-Bix

**Comment by thisisdano** [comment]
Done in https://github.com/uswds/uswds-for-designers/pull/81 as well as the Adobe XD version
