### ISSUE TITLE
Create emergency response icons

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3771]
## Milestones

DESIGN ASSETS
- [x] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback - done Wed 11/4
- [x] 20% - Draft user story & clarify the problem(s) / user needs **- due Mon 11/9**
- [x] 30% - Low-fi design review **- due Mon 11/9**
- [x] 40% - Get community feedback on initial, Hi-fi designs **- due Mon 11/9**
- [ ] 50% - Hi-fi Sketch assets review **- due Wed 11/18**
- [ ] 60% - Hi-fi Adobe XD assets review **- due Fri 11/27**
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files **- due Wed 12/2**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

GUIDANCE
- [x] 10% - Summarize insights from research (desk + interviews) **- due Mon 11/9**
- [x] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) **- due Tue 11/10**
- [x] 40% - Get community feedback on draft guidance **- due Tue 11/17**
- [x] 50% - Draft guidance review no. 2 (accessibility focus) **- due Tue 11/24**
- [x] 60% - Draft guidance review no. 3 (w/ Dan) **- due Wed 12/2**
- [x] 80% - Add component to research report and slide deck **- due Wed 12/2**
- [ ] 100% - PR approved by Dan **- due Fri 12/4**

CODE
- [x] 10% - Code review no. 1 (Federalist preview) - interaction design focus **- due Tue 11/10**
- [x] 20% - Code review no. 2 (Federalist preview) - visual design focus **- due Fri 11/13**
        _*We have access to crossbrowsertesting.com and AWS Workspace with NVDA for a11y testing_
- [x] 40% - Get community feedback or conduct tests with users, round 1 **- due Wed 11/18**
- [x] 60% - Code review no. 3 (Federalist preview) - accessibility focus **- due Wed 11/25**
- [x] 80% - Get community feedback or conduct tests with users, round 2 **- due Tue 12/1**
- [x] 100% - PR approved by Dan **- due Fri 12/4**

## Random thoughts

consistent iconography across agency websites
font awesome as an option

- RESEARCH and TESTING into effectiveness in communicating
- Suite of icons for common information types and actions (possibly from Font Awesome)
- Guidance around color usage, size, placement, accessibility

10/14 review Dan no. 1

**Comment by Ben-Judy-Flexion** [comment]
Here's a [notes doc from a kick-off conversation](https://docs.google.com/document/d/1lZweko9RlF9si5122IMhWP1HqrBxf2M_A_U3KCWFu6Y/edit) between me and @ardenk

**Comment by Ben-Judy-Flexion** [comment]
I [asked a few questions](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1603737335200900) about how people are using icons on this sites, on Slack #uswds-public

**Comment by ardenk** [comment]
Moved the notes doc to GSA drive, [here's the current notes doc](https://docs.google.com/document/d/1CaQp0y1-Y5-iNq6_BzRFtiklFIEcHwickf1zSfWBjAM/edit)

**Comment by Ben-Judy-Flexion** [comment]
Got a thumbs-up from @sknep and @kimschulke on the 10% design milestone, `Collect and analyze examples, collect research insights, draft list of features, inventory existing icons`. Will continue to add to these and iterate as the project progresses, but we have a good start on these things.

**Comment by ardenk** [comment]
Met with Dan to agree on next steps. @jaredcunha is working on implementation and I am making a 2-pager for community feedback. Ben or I can also pick up writing up usability guidelines.

**Comment by jaredcunha** [comment]
Unlike the other components, the work on this project will also involve updates to the USWDS Gulpfile, which moves site assets from the node modules folder into a project so they can be used. https://github.com/uswds/uswds-gulp/

The changes I have to this file will be reviewed for community feedback in a prototype that developers can use to customize their own svg sprite.
