### ISSUE TITLE
Better mobile support for tables

### ISSUE THREAD

**Issue by debjudy** [uswds/uswds#3773]
Displaying large amounts of emergency data to the public, should handle horizontal scrolling, driven towards large datasets, reformat for mobile

Rules for color and data representation, Sortable tables, other table variations (stacked, responsive, etc)
displaying large amounts of emergency data to the public, should handle horizontal scrolling, driven towards large datasets

10/14 review # 4 on Dan's List
**DESIGN ASSETS**
- [x] 10% - Collect and analyze examples, draft research insights, draft list of features [[Mural](https://app.mural.co/t/flexion6734/m/flexion6734/1604698717339/bed19570488df24ca3d72139f80e1842eb942b11)]  - **11/2**
- [x] 20% - Low-fi design review [[Figma](https://www.figma.com/file/sNzPSmxJEeg9LF4BZQfpJy/Responsive-Tables-WIP?node-id=1%3A4)] - **11/5**
- [ ] 40% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

**GUIDANCE**
- [x] 10% - Summarize insights from research (desk + interviews) - **11/2**
- [x] 20% - Draft guidance review #1 (minimum 2 bullets each section)  - **11/6** [[Doc](https://docs.google.com/document/d/1DOsQqvky7Ti6xqD7KqPiotoBqnoBwMO_xpooLOtFLXQ/edit#heading=h.2sshygvkz0ad)]
- [x] 40% - Send out for community feedback on draft guidance - **11/10** [[Slack](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1605105527238500)]
- [x] 60% - Draft guidance review #2 - **11/24** [[Federalist](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/accelerator/3773-mobile-tables/components/table/)]
- [x] 80% - Draft guidance review #3 (w/ Dan) - **Sent 11/25**
- [ ] 100% - PR approved by Dan

**CODE**
- [x] 10% - Code review #1 (Federalist preview) - interaction design focus  - **11/10** [[Federalist](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3773-mobile-tables/components/detail/table.html)]
- [x] 20% - Code review #2 (Federalist preview) - visual design focus  - **11/17**[[Federalist](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3773-mobile-tables/components/detail/scrollable-table.html)]
- [x] 40% - Get community feedback or conduct tests with users, round 1  - **11/13**
- [x] 60% - Code review #3 (Federalist preview) - accessibility focus  - **11/24** [[Federalist](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/accelerator/3773-mobile-tables/components/detail/table--default.html)]
- [x] 80% - Get community feedback or conduct tests with users, round 2  - **11/24**
- [ ] 100% - PR approved by Dan - **11/26**

**Comment by sknep** [comment]
**DESIGN ASSETS**
- [x] 10% - Collect and analyze examples, draft research insights, draft list of features
- [ ] 20% - Low-fi design review
- [ ] 40% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

**GUIDANCE**
- [ ] 10% - Summarize insights from research (desk + interviews)
- [ ] 20% - Draft guidance review #1 (minimum 2 bullets each section)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 60% - Draft guidance review #2
- [ ] 80% - Draft guidance review #3 (w/ Dan)
- [ ] 100% - PR approved by Dan

**CODE**
- [ ] 10% - Code review #1 (Federalist preview) - interaction design focus
- [ ] 20% - Code review #2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review #3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

**Comment by sknep** [comment]
Mobile enhancements for tables is now available for review:
Guidance: https://github.com/uswds/uswds-site/pull/1095
Code: https://github.com/uswds/uswds/pull/3825
