### ISSUE TITLE
Component Template

### ISSUE THREAD

**Issue by Ben-Judy-Flexion** [uswds/uswds#3807]
## Milestones

DESIGN ASSETS
- [ ] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [ ] 20% - Draft user story & clarify the problem(s) / user needs
- [ ] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [ ] 10% - Summarize insights from research (desk + interviews)
- [ ] 20% - Draft guidance review no. 1 (minimum 2 bullets each section)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (accessibility focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add component to research report and slide deck
- [ ] 100% - PR approved by Dan

CODE
- [ ] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [ ] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan
