### ISSUE TITLE
Update PL components and SASS imports

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3820]
Refactor style sheets folder.

**T2C**
- [x] Sync 2.10.0, remove SASS modules
- [x] compile and test

**DOD**
- [x] target finish date 1/11
- [x] review w client 1/8
- [x] dist folder outputs css, images, fonts, js and sass folders properly compiled

**Comment by jAigret-Bix** [comment]
@chazchumley - review w client 1/8. 2.10.0 is 85% synced and sass modules removed. Work will be completed EOD 1/11 with another review on 1/12. A PR will be created. 
Next steps: New organizational structure will be received from Dan, to send EOD 1/8. New structure will be incorporated and out standing PRs folded in. See #3931

**Comment by chazchumley** [comment]
@jAigret-Bix This is finished

**Comment by mejiaj** [comment]
Available in following branches:
https://github.com/uswds/uswds/tree/library--develop
https://github.com/uswds/uswds/tree/library--main
