### ISSUE TITLE
Wrap inputs in label tag

### ISSUE THREAD

**Issue by mmazanec22** [uswds/uswds#3836]
### Describe the bug
In Internet Explorer 10 on Windows 7 using the [pattern described in the USWDS documentation](https://designsystem.digital.gov/form-controls/08-file-input/), only the label is clickable and the area that appears to be clickable does not trigger any events.  Changing the component code to wrap the entire thing in the label fixed it:
```
    <label htmlFor={id}>{label}
      {ariaDescribedByText && (
        <span id={`${id}-aria-describedby`}> {ariaDescribedByText}</span>
      )}
      <input
        id={id}
        type="file"
        className="usa-file-input"
        aria-describedby={
          ariaDescribedByText ? `${id}-aria-describedby` : undefined
        }
        onChange={onChange}
      />
    </label>
```

### Steps to reproduce the bug
1. Go to [the example from the docs](https://designsystem.digital.gov/form-controls/08-file-input/) (or a page that implements that pattern) in IE 10 on Windows 7
2. Click within the file input box-- there will be no popup to select a file
3. Click on the label-- there will be a popup to select the file

### Expected behavior
I would expect that clicking on the blue underlined text would trigger the file selection popup.

### System setup
- **USWDS version:**  whatever is in the docs (we're on 2.9.0 and this also happens there)
- **Device:**  Browserstack-- unknown
- **Operating system:**  Windows 7
- **Browser and version:**  IE 10

### Additional context
Wrapping the input int he label fixes this issue, so it may just be a matter of updating the docs if that is the intended pattern.

**Comment by thisisdano** [comment]
USWDS does not support IE10, but if someone can submit a PR that fixes this, I'm happy to merge it in.

**Comment by mejiaj** [comment]
### Todo

- [x] HTML spec confirms this pattern - https://html.spec.whatwg.org/multipage/forms.html
- [ ] Look at WCAG patterns.
- [ ] Confirm if we're following recommended standards.

**Comment by annepetersen** [comment]
Hi there: this is one of many submitted PRs/issues that have languished here. USWDS is currently understaffed, so I'm closing items that aren’t as high on the priority list right now, including this one, unfortunately.
