### ISSUE TITLE
Pagination: User testing plan

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#3961]
Description: Create a process surrounding user testing for pagination component. Define goals and desired outcomes of pagination test. 

**Tasks**
- [x] review current state of Pagination, previous research, community feedback, guidance
- [x] develop goals for test, What are we trying to learn? How will we conduct the test?
- [x] develop pilot test plan (include recruitment process)
- [x] review test plan w team and client

**Acceptance Criteria**
- [x] testing plan is developed using best practice and aligns with PRA restrictions

**Definition of Done**
- [x] [document](https://docs.google.com/document/d/1MVH1Nb8JrDFgVhimDafjOJi2lTuCxeFY2UK4oXZ9gOo/edit#) to share out that communicates: goals, methods, participants, etc [PDF Version](https://drive.google.com/file/d/1RR58prspXIDXon_lzZuQPWogQqIKDsvE/view?usp=sharing)
- [x] Shared to [Slack](https://gsa-tts.slack.com/archives/C050HRGN7/p1613510957139300) for client notification 2/16
- [x] create next issue to implement testing plan https://github.com/uswds/uswds/issues/4018
- [x] capture content in [research plan](https://docs.google.com/document/d/1r63UHEelNGnA3q2KKK4ekxqjRgs4XQaK5RxotceGJds/edit#heading=h.ht8mgoie1obe)

**Comment by jAigret-Bix** [comment]
Per @thisisdano  on 2/19, core team will move forward with next steps - recruitment and testing. JA 2/22: issue is complete and will closed. @afeijoo
