### ISSUE TITLE
2021: Accelerator followup

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds#4034]
**Description** Follow up and close out work pertaining to accelerator components or `Next` report

### Related issues
- [ ] [Table sorting](https://github.com/uswds/uswds/issues/3935)
- [ ] [Modals](https://github.com/uswds/uswds/issues/3936)
- [ ] [Link guidance](https://github.com/uswds/uswds/issues/3831)
- [ ] [Icon list](https://github.com/uswds/uswds/issues/3772)
- [ ] [404 template and guidance](https://github.com/uswds/uswds/issues/3693)
- [ ] [Derivative works language](https://github.com/uswds/uswds/issues/3945)
- [ ] [Printer friendly formatting](https://github.com/uswds/uswds/issues/3940)
- [ ] [Updated design assets](https://github.com/uswds/uswds/issues/4011)
- [ ] [Checkbox/radio printing issues](https://github.com/uswds/uswds/issues/3137)
- [ ] [Icon usage in design assets](https://github.com/uswds/uswds/issues/3494)
- [ ] [Spanish signin templates](https://github.com/uswds/uswds/issues/4012)
- [ ] [Spanish 404 template](https://github.com/uswds/uswds/issues/4012)
- [ ] [Mobile nav does not make background inert](https://github.com/uswds/uswds/issues/3527)
- [ ]
