### ISSUE TITLE
Create Checklist guidance

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#4043]
## Description

Create documentation page for [Checklist component ](https://components.designsystem.digital.gov/components/detail/validation.html) so users know it exists and can implement it properly. You can view the Checklist in Fractal [here](https://components.designsystem.digital.gov/components/detail/validation.html).

- [x] 10% Research guidance
- [x] 20% Write [draft guidance](https://docs.google.com/document/d/1s8eoQUsVkUPRoGS76-6PmS04MKPuwPFjVWFaPE9iKu0/edit) updated 1/7
- [ ] 30% Internal team review 
- [ ] 40% edit and updates
- [ ] 60% Client review no. 1 
- [ ] 70% edit and updates
- [ ] 80% Client review no. 2 /approval
- [ ] 100% create issue in site, create issue for design assets

## Additional information [optional]

We already have this related issue on adding undocumented components uswds/uswds-site#808. But this is specific to the Checklist to create content and page.

**Comment by annepetersen** [comment]
USWDS is currently understaffed, so I'm closing items that aren’t as high on the priority list right now, including this one, unfortunately.
