### ISSUE TITLE
Support Spanish version of pagination component

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds#4158]
**Tasks**
- [x] Reach out to USAGov en Español team
- [x] Draft [copy for Spanish code variants](https://docs.google.com/document/d/1kvUDW0pNmOEf_xlQv6-0BtaJiizQWFK9dCv5oTIs8GQ/edit#):lock:
- [x] Review and update guidance for for multilingual considerations, if any
- [x] Update YML settings file (similar to Search and Banner components)
- [x] Update Spanish code variations on USWDS site
- [x] Update guidance on USWDS site

 
the [PR is here](https://github.com/uswds/uswds/pull/4121). 
 
[Pagination default](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-library-add-pagination/?p=components-usa-pagination) and [Pagination Infinite](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-library-add-pagination/?p=components-usa-pagination--infinite)

**DOD**
All tasks above are done.

**Comment by afeijoo** [comment]
@mejiaj The [Spanish text for pagination](https://docs.google.com/document/d/1kvUDW0pNmOEf_xlQv6-0BtaJiizQWFK9dCv5oTIs8GQ/edit):lock: is ready for you. 

There aren't any updates to the guidance.
