### ISSUE TITLE
USWDS - Character count: Clarify initialization requirements

### ISSUE THREAD

**Issue by mike-usa** [uswds/uswds#4399]
### Bug Description
Character count component does not work after adding an element dynamically on the page.

### Steps to reproduce the bug
1. Navigate to a USWDS page (https://designsystem.digital.gov/)
2. Open browser console
3. Paste the following code:
   ```javascript
   const container = document.querySelector('#main-content')
   const newElement = document.createElement('div')
   newElement.innerHTML = `
   <div class="grid-row">
     <div class="grid-col">
       <div class="usa-character-count">
         <div class="usa-form-group>
           <label class="usa-label" for="example">Example</label>
           <textarea class="usa-textarea usa-character-count__field" maxlength="255"></textarea>
         </div>
         <span class="usa-hint usa-character-count__message" aria-live="polite">Enter up to 255 characters</span>
       </div>
     </div>
   </div>
   `
   container.prepend(newElement.children[0])
   ```
4. Type in the textarea

### Expected behavior
Expect dynamically-added `usa-character-count` component to update count after being added to the page.

### Considerations
1. consider adding documentation to bind events on new elements/components after page load if it does not exist -- make more prominent and easier to find if it does exist
1. do not require manual initialization of new components
   - bind component's listener on ancestor element (e.g., `body`)
   - as opposed to a component/keypress listener on ancestor element, it may be more efficient to place a `DOMNodeInserted` event listener, which then iterates over component library for js-dependent ocmponents and and initializes them

**Comment by mike-usa** [comment]
UPDATE: After looking at how the component is configured ([js/components/character-count.js](https://github.com/uswds/uswds/blob/develop/src/js/components/character-count.js)), I've discovered that `setupAttributes()` removes the `maxlength` attribute from the the input element (i.e. `.usa-character-count__field`) and applies it to the component wrapper element (i.e. `div.usa-character-count`).  

The `updateCountMessage()` function has a short-circuit clause to exit if the attribute is not found.  For my case where components are added after the page load, applying the `data-maxlength` to the wrapper has resolved the issue.

```javascript
const container = document.querySelector('#main-content')
const newElement = document.createElement('div')
newElement.innerHTML = `
<div class="grid-row">
  <div class="grid-col">
    <div class="usa-character-count" data-maxlength="255">
      <div class="usa-form-group>
        <label class="usa-label" for="example">Example</label>
        <textarea class="usa-textarea usa-character-count__field"></textarea>
      </div>
      <span class="usa-hint usa-character-count__message" aria-live="polite">Enter up to 255 characters</span>
    </div>
  </div>
</div>
`
container.prepend(newElement.children[0])
```

**Comment by mejiaj** [comment]
@mike-usa thanks for sharing your findings. I'll look into this and confirm. 

- [ ] Is this the desired method
- [ ] Are any documentation updates are required

**Comment by mejiaj** [comment]
@mike-usa thanks for posting all of this information, I can confirm adding `data-maxlength` to character count markup does work when adding component dynamically.

We have a few options:
1. Leave code as-is and write guidance for adding this component dynamically on [Character Count component page](https://designsystem.digital.gov/components/character-count/) - **[low LOE]**
2. Run the `setupAttributes()` function once component has been added  **[potentially medium LOE]** ⁕

⁕ This would require us to use something like [Mutation Obvserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), which seems to be the best practices for listening for added/removed DOM elements.

**Comment by mejiaj** [comment]
Related to #4055.

**Comment by mejiaj** [comment]
## Todo

- [ ] Confirm if we're providing tools to properly initialize
- [ ] Confirm guidance is accurate

**Comment by annepetersen** [comment]
Hi there: this is one of many submitted PRs/issues that have languished here. USWDS is currently understaffed, so I'm closing items that aren’t as high on the priority list right now, including this one, unfortunately.
