### ISSUE TITLE
Phase 1: Windows HC Fixes

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4517]
Complete fixes outlined by audit to components in Windows HC mode. 

- [x]  **Accordion** - Outline & expand/collapse icons missing for menu items (which makes it hard for users to tell it is an expandable accordion) - Fixed in #4521
- [x] **Banner** - Chevron missing (without those, users cannot tell they can expand the banner for more information) - Resolved in https://github.com/uswds/uswds/pull/4529
- [x] **Checkbox** - Checkboxes do not show in high contrast mode - Fixed in #4509 
- [x]  **Header** - Fixed in #4485 
- [x] **Radio Buttons** - Radio buttons are invisible and do not show which is selected. - Fixed in #4509 
- [x] **Range Slider** - Slider handle missing an outline and becomes negative space in between the range bar - Fixed in #4510
- [x] **Pagination** - Selected page should have a bold border or different color background. In high contrast it isn't possible to see what page the user is currently on. - Fixed in #4523 
- [x] **Footer** - Social media icons missing. Chevron icon missing from mobile view -  Resolved in #4528
