### ISSUE TITLE
Phase 2: Windows HC Fixes

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4518]
Fixes identified via audit for components in Windows HC mode.

- [x]  **Header** - Fixed in #4485 
- [ ] **Identifier** - External website icons missing
- [ ] **Pagination** - Selected page should have a bold border or different color background. In high contrast it isn't possible to see what page the user is currently on.
- [x] **Radio Buttons** - Radio buttons are invisible and do not show which is selected. - Fixed in #4509 
- [x] **Range Slider** - Slider handle missing an outline and becomes negative space in between the range bar - Fixed in #4510
- [ ] **Time Picker** - Missing chevron icon

**Comment by mahoneycm** [comment]
Resolved in #4610
