### ISSUE TITLE
USA Accordion: Prototype hidden-until-found attr for SEO

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#4799]
The `hidden=until-found` attribute for accordion body allow content to be findable with in-page search.

Issue created from [USWDS Slack thread](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1654261009509509).

**Comment by DK1999** [comment]
Some more info: https://developer.chrome.com/articles/hidden-until-found/

**Comment by mejiaj** [comment]
Thanks for sharing that guidance. It seems there are two possible techniques:

1. The `hidden="until-found"` attribute in HTML. [MDN →](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden)
2. Using CSS  `content-visibility` property. [MDN →](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility)

The 2nd technique seems better supported, would be less tedious to users, and could be a progressive enhancement to the existing component.

**Comment by brunerae** [comment]
@mejiaj what does this Issue need to be closed?

**Comment by ajfarkas** [comment]
I would really love to see this implemented. Mainly, I'm looking forward to [this change](https://github.com/uswds/uswds/pull/5644/files#diff-634c09a317fa942630ab47405529a02a66f4bc282dda17c08ad62c7f78ecbc08) in the linked PR.

We would like to link to an id inside an accordion, so that we can direct developers to a specific part of our documentation. `hidden="until-found"` would allow that, which is currently not possible.

**Comment by mejiaj** [comment]
## Todo

Overall, need to explore ways to add this feature in a way that minimizes impacts to accordions. For example, resolving spacing issues in [live site](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-test-accordion-hidden-content/components/accordion/).

- [ ] Update PR branch with latest from `develop`.
- [ ] Confirm if class is needed for hidden until found. _This could help separate enhanced vs fallback styles more cleanly._
- [ ] Confirm if normalize really needs an override. Alternatively, consider setting via class if hidden until found is supported.
