### ISSUE TITLE
TEMPLATE: Pattern Issue with AC

### ISSUE THREAD

**Issue by Nijal-collab** [uswds/uswds#4804]
Description: text
Documentation: [Document link](#) | [Preview link](#)
Implicated Component(s): [GH Issue link](#) | [Component Page link](#)

### Team

- [ ] Problem to solve, name, description
- [ ] Team review of [DEIA lenses](https://docs.google.com/document/d/1nHwYseekmMCzOSELwEtNgnBSnoqBTElD00GqeWeSuGU/edit) applied to pattern/sub-pattern
* guidance implications
* wireframe implications
* component implications

### Milestones
- [ ] Check heading order (@thisisdano)
- [ ] First guidance review (@thisisdano)
- [ ] First design review (@thisisdano)
- [ ] First code review (@mejiaj)
- [ ] Second guidance review (@thisisdano)
- [ ] Second design review (@thisisdano)
- [ ] Second code review (@mejiaj)
- [ ] Further content review (_optional_)
- [ ] Further dev review (_optional_)
- [ ] Merge code into uswds
- [ ] Update guidance to new formatting (@thisisdano)
- [ ] Merge guidance & design assets into docs
- [ ] Update design assets if necessary (@thisisdano)

- - -

DESIGN ASSETS
- [ ] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [ ] 20% - Draft user story & clarify the problem(s) / user needs
- [ ] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [ ] 10% - Summarize insights from research (desk + interviews) & DEIA considerations - done ##/##
- [ ] 20% - Draft guidance review no. 1 [See Fields](https://docs.google.com/document/d/1HLpbXY4sXo0oj-BJnvQ4klEXNwsOof_naFiqPLoZgTA/edit) - done ##/##
- [ ] 30% - Evaluate cross-linking opportunities (implicated components, others?)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (DEIA focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add pattern to research report and slide deck
- [ ] 100% - PR approved by Dan

CODE (If applicable)
- [ ] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [ ] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

**Comment by maomeara63** [comment]
@jonadecker Just checking on the Milestone tags. Lots of review for Dan and who is the mejiej person?

**Comment by jonathanbobel** [comment]
To @maomeara63's point - that is a lot for @thisisdano to review - should just make sure we need his check on each one of these steps. Besides that, it looks good.
