### ISSUE TITLE
TEMPLATE: Component Issue with AC

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds#4807]
Description: text
Code:  [GH Issue link](#) | [Preview link](#)
Guidance documentation: [Document link](#)
Supports Pattern(s): [GH Issue link](#)

### Milestones
- [ ] First code review (@thisisdano)
- [ ] Check heading order (@thisisdano)
- [ ] First guidance review (@thisisdano)
- [ ] Second code review (@mejiaj)
- [ ] Second guidance review
- [ ] Further content review (_optional_)
- [ ] Link guidance (@thisisdano)
- [ ] Update guidance to new formatting (@thisisdano)
- [ ] Merge guidance into docs
- [ ] Merge code into uswds
- [ ] Update design assets if necessary (@thisisdano)

- - -

DESIGN ASSETS
- [ ] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [ ] 20% - Draft user story & clarify the problem(s) / user needs
- [ ] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [ ] 10% - Summarize insights from research (desk + interviews)- done ##/##
- [ ] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) - done ##/##\
- [ ] 30% - Evaluate cross-linking opportunities (implicated patterns, others?)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (DEIA focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add component to research report and slide deck
- [ ] 100% - PR approved by Dan

CODE
- [ ] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [ ] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

**Comment by maomeara63** [comment]
@jonadecker Under "Milestones" there are people tagged for specific tasks. 1. Is Dan appropriately tagged to check heading order and do the first review? Who is the person tagged on second code review?

Also, under guidance 20% it says "min 2 bullets each section." I'm not clear on what that is. Is it a holdover from Accelerator?

**Comment by jonathanbobel** [comment]
I think this looks good @jonadecker - am also curious about the need for _2 bullets for each section in Guidance - 20%_. If there was a specific reason for this we can keep it in.

**Comment by jonadecker** [comment]
I don't think the AC for a component has changed since Accelerator so I believe it simply establishes a minimum for each section. I'll check if that jibes with current component guidance.
