### ISSUE TITLE
Component: Input Masks

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds#4852]
Description: text
Code:  [GH Issue link](#) | [Preview link](#)
Guidance documentation: [Document link](#)
Supports Pattern(s): [GH Issue link](#)

### Milestones
- [ ] First code review (@thisisdano)
- [ ] Check heading order (@thisisdano)
- [ ] First guidance review (@thisisdano)
- [ ] Second code review (@mejiaj)
- [ ] Second guidance review
- [ ] Further content review (_optional_)
- [ ] Link guidance (@thisisdano)
- [ ] Update guidance to new formatting (@thisisdano)
- [ ] Merge guidance into docs
- [ ] Merge code into uswds
- [ ] Update design assets if necessary (@thisisdano)

- - -

DESIGN ASSETS
- [ ] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [ ] 20% - Draft user story & clarify the problem(s) / user needs
- [ ] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [ ] 10% - Summarize insights from research (desk + interviews)- done ##/##
- [ ] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) - done ##/##\
- [ ] 30% - Evaluate cross-linking opportunities (implicated patterns, others?)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (DEIA focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add component to research report and slide deck
- [ ] 100% - PR approved by Dan

CODE
- [ ] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [ ] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

**Comment by mitchmoccia** [comment]
https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jb-inclusive-patterns-input-mask/iframe.html?args=&id=components-form-inputs-text-input-mask--input-mask&viewMode=story

- - update Jon's original branch with some of the features of the newer branch
  - e.g. kept the input shell wrapper pattern
- changed from keydown event to keyup
  - this provided a quicker replacement of the masked character with the typed in value
  - looks more responsive and solid
- changed the masked character from X to _  (an underscore)
- lightened up the mask characters
- updated unit test scripts to use the keyup event and for phone expect underscores instead of X's
- ensured that data can be pasted into fields
  - data pasted conforms to the regex pattern
- ensured that auto complete works

**Comment by thisisdano** [comment]
Completed
