### ISSUE TITLE
Component: Language Selector

### ISSUE THREAD

**Issue by jonadecker** [uswds/uswds#4853]
Description: text
Code:  [GH Issue link](#) | [Preview link](#)
Guidance documentation: [Document link](#)
Supports Pattern(s): [GH Issue link](#)

### Milestones
- [ ] First code review (@thisisdano)
- [ ] Check heading order (@thisisdano)
- [ ] First guidance review (@thisisdano)
- [ ] Second code review (@mejiaj)
- [ ] Second guidance review
- [ ] Further content review (_optional_)
- [ ] Link guidance (@thisisdano)
- [ ] Update guidance to new formatting (@thisisdano)
- [ ] Merge guidance into docs
- [ ] Merge code into uswds
- [ ] Update design assets if necessary (@thisisdano)

- - -

DESIGN ASSETS
- [ ] 10% - Collect and analyze examples;  draft research insights and list of features for team/client feedback
- [ ] 20% - Draft user story & clarify the problem(s) / user needs
- [ ] 30% - Low-fi design review
- [ ] 40% - Get community feedback on initial, Hi-fi designs
- [ ] 50% - Hi-fi Sketch assets review
- [ ] 60% - Hi-fi Adobe XD assets review
- [ ] 80% - Sketch and XD assets review w/ Dan + merged into master working files
- [ ] 100% - PR approved by Dan

GUIDANCE
- [ ] 10% - Summarize insights from research (desk + interviews)- done ##/##
- [ ] 20% - Draft guidance review no. 1 (minimum 2 bullets each section) - done ##/##\
- [ ] 30% - Evaluate cross-linking opportunities (implicated patterns, others?)
- [ ] 40% - Get community feedback on draft guidance
- [ ] 50% - Draft guidance review no. 2 (DEIA focus)
- [ ] 60% - Draft guidance review no. 3 (w/ Dan)
- [ ] 80% - Add component to research report and slide deck
- [ ] 100% - PR approved by Dan

CODE
- [ ] 10% - Code review no. 1 (Federalist preview) - interaction design focus
- [ ] 20% - Code review no. 2 (Federalist preview) - visual design focus
- [ ] 40% - Get community feedback or conduct tests with users, round 1
- [ ] 60% - Code review no. 3 (Federalist preview) - accessibility focus
- [ ] 80% - Get community feedback or conduct tests with users, round 2
- [ ] 100% - PR approved by Dan

**Comment by sawyerh** [comment]
@jonadecker @mitchmoccia @thisisdano Is this a wishlist/feature request, or a component that is officially on a roadmap?

**Comment by thisisdano** [comment]
Completed
