### ISSUE TITLE
Compile and compare functionality from old to new (after change to @import for JS)

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#4988]
Test `package.json` entrypoints to find differences with CommonJS and ESM imports. 

## Tasks

- [x] ESM imports with ESBuild
- [x] ESM imports with Rollup
- [x] CJS with Rollup
- [x] Compare output between ESM & CJS
- [x] Update notes on ESM alpha [currently #5091]

## Working branches

- [uswds/uswds-sandbox#jm-test-esm-esbuild
](https://github.com/uswds/uswds-sandbox/tree/jm-test-esm-esbuild)
- [uswds/uswds-sandbox#jm-test-esm-rollup
](https://github.com/uswds/uswds-sandbox/tree/jm-test-esm-rollup)
- [uswds/uswds-sandbox#jm-test-esm-rollup-cjs
](https://github.com/uswds/uswds-sandbox/tree/jm-test-esm-rollup-cjs)

### ESBuild

- Need to compare with CJS
- Unused imports aren't removed see [uswds/uswds-sandbox/src/assets/project/js/index.js:5](https://github.com/uswds/uswds-sandbox/blob/5e2a6ac97f42cc7d4b731930d5673a6415fc36bd/src/assets/project/js/index.js#L5-L7)
- Can't resolve `require()` when importing ESM

### RollupJS

- Handles both ESM and CJS imports just fine

### File sizes

| Tool used | Size |
|--------|--------|
| ESbuild | 38KB |
| Rollup | 31KB |
| TK | TK |

**Comment by brunerae** [comment]
Closing as complete.
