### ISSUE TITLE
USWDS - Component lifecycle: Outline plan and deliverables

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5122]
## Task list
- [x] Create tasks to complete component lifecycle work
    - Tasks have been outlined under "Define Component Lifecycle" in the project [Epics](https://github.com/orgs/uswds/projects/8/views/16) tab

## Deliverables
1. Flow chart that visually demonstrates the full component lifecycle
    - [ ] #5138 
1. A list of each phase in the cycle with a written summary for each
    - [ ] #5140
1. Evaluation criteria document
    - [ ] #5139 
1. Proposal template
    - [ ] #5141 
1. Guidance documentation template
    - [ ] https://github.com/uswds/uswds-site/issues/2003
1. Design for how to display a component's current status on uswds-site
    - [ ] https://github.com/uswds/uswds-site/issues/2003
1. Communications plan for updating public on progress
    - [ ] #5143
1. [TBD] Blog post (or similar) explaining why we defined this process
    - HOLD - Specifics pending the plan outlined in #5143
