### ISSUE TITLE
USWDS - Bug: Tooltip example isn't typical of tooltip usage

### ISSUE THREAD

**Issue by mgifford** [uswds/uswds#5343]
### Describe the bug

The USWDS tooltip component provides an example here https://designsystem.digital.gov/components/tooltip/

But who uses tooltips on a button styled like that? They are almost always tied to form elements and either styled as an "i" or a "?" so that folks know what to expect.

So the example should highlight that. 

### Steps to reproduce the bug

Compare example with usage on .gov sites. 

### Expected Behavior

The example should look something like this:
https://codepen.io/mgifford/pen/vYQKbxG

Not this is a rough prototype. It's not even using the USWDS as I had difficulty getting it to work properly on codepen.  Fortunately I could borrow another prototype which is close. 

### Screenshots

<img width="872" alt="Screenshot of existing site." src="https://github.com/uswds/uswds/assets/116832/6020a1cc-86f3-4cab-9455-e68f16f97dc0">

vs screenshot of what I'm proposing. 

<img width="803" alt="Screenshot of proposal with form elements" src="https://github.com/uswds/uswds/assets/116832/b2a45d39-5ff9-429b-af2b-de156c5b4cd1">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment]
### Todo

- [ ] Explore recommended use cases for tooltips.
- [ ] Find W3C examples.
- [ ] Work with UX/A11Y to get additional recommendations.

**Comment by amyleadem** [comment]
@jaclinec 
Can you explore the recommended patterns for using tooltips? We are curious about how/if we should update our component examples.

**Comment by sperro** [comment]
I second this. The documentation says "Any element with the class name usa-tooltip and a title attribute will become a tooltip" which is not the case. It only works with button elements. I would like the option to use this on icons and other elements.

**Comment by annepetersen** [comment]
As I noted elsewhere, I'm currently doing a bunch of closing of stale issues for right now, given current bandwidth (hopefully with the intent to reconsider them later)
