### ISSUE TITLE
USWDS - JSON tokens: Assess if style dictionary is the tool we want to use

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5437]
## Tasks

Research style dictionary.

- [x] List alternative tools
  - [x] List pros/cons
  - [x] Identify level of maintenance
  - [x] Approximate bundle size
  - [x] Output customization options
- [x] Document findings
- [x] Present findings to team
- [x] Decide which tool we want to use

**Comment by mahoneycm** [comment]
## Update Nov 15th

We met and discussed possible alternatives yesterday. After analysis of Theo, Design System Utils, and Dragoman, we've decided Style-dictionary is the best route forward.

[Style-Dictionary Alternatives Discussion meeting notes](https://docs.google.com/document/d/1vT-_PxOTWhQKnXu5k5CXTjDv8sc0ecz88OsLPnrgTNo/edit) 🔒
[Style-Dictionary Alternatives outline](https://docs.google.com/document/d/1yAh0v5rx4__xxW7U9O4u9PetWqQPkdBTOjWipOm_SfA/edit?usp=sharing) 🔒
