### ISSUE TITLE
USWDS - JSON tokens: Create strategy for converting system tokens to JSON

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5438]
## Objective

We've identified system tokens to convert to JSON and will create tasks to split work.

## Tasks

- [x] We have a list of system tokens to convert.
- [x] We know the technical requirements to converting these tokens.
- [x] Convert system tokens to JSON

**Comment by mejiaj** [comment]
@brunerae I've re-worked this to focus only on system tokens. 

The ideation for semantic/component tokens can be reviewed or bumped as we learn more.

**Comment by ethangardner** [comment]
This work has been started in the https://github.com/uswds/uswds-elements repo. A strategy has been mapped out and is ready to start. Closing the issue over in this repo since they use different project boards.
