### ISSUE TITLE
CC a11y audit only - radio button component

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5504]
Audit the radio button component for WCAG compliance and critical checklist checks using three manual accessibility testing methods.
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
This ticket will be considered done once the following content has been written and associated WCAG checks are in place for the radio button component:
WCAG criteria related to [radio button component](https://designsystem.digital.gov/components/radio-buttons/) elements
How to perform manual testing (critical checklists) and related user-focused questions for downstream teams to test.
 a. Zoom mag to 200% b. Keyboard c. JAWS

 The results will be added into the spreadsheet. You can use this document as a starting reference: https://docs.google.com/document/d/1l8KP9A77rg6IF7YME0CvadMMczZKU5FMHvBqkyWFIfM/edit?usp=sharing
[List of all components is here](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

### Todo

- [x] Test radio component on site with JAWS
- [ ] Test radio component on site with NVDA
- [x] Add it to the spreadsheet.

#### Bugs discovered

- [ ] Create required field radio button example for error handling testing

#### Enhancements

- [ ] TK

**Comment by amycole501** [comment]
This component audit will help us evaluate the issue here https://github.com/uswds/uswds/issues/5487

**Comment by amycole501** [comment]
These form elements will use a phased approach:
We will evaluate the component in a non-required-field state and will tackle error handling and prevention later
Will also tackle suggestions for more variations of the buttons/form elements in a separate column in the spreadsheet.

**Comment by brunerae** [comment]
Closing as complete
