### ISSUE TITLE
USWDS - JSON tokens: Determine which tokens to convert to JSON

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5507]
## Tasks
Create a tiered plan for converting USWDS Sass tokens to JSON.

- [ ] Determine criteria for converting
  - [x]  Identify `system`, `semantic`, and `component` layers of tokens
  - [x] Use layers of color tokens as an example for converting
  - [ ] Prototype 
    - [ ] Converting font-size
    - [ ] Converting z-index
- [ ] **Spike:** What does a token mean in terms of typography (_ex: line-height_)? _Where output value is dependent on input value of two tokens_.
- [x] Identify which token families should be converted to JSON (ex: `Color` → `Space` → `Type` )
- [x] Prioritize groups that should be converted first
- [x] Document and present findings to team

For example, color and spacing tokens would likely be converted first and could be labeled as Tier 1.

## Reference
[Token file spreadsheet](https://docs.google.com/spreadsheets/d/1gP8OTD3Od3CuTxkNdc5yiLAovTeyFNG3HD3vJ1AaKLQ/edit#gid=0) (Google Docs :lock:)
[Notes from our Jan '24 JSON Tokens meeting](https://docs.google.com/document/d/1N3s_qgILXya49xmWEHFht05J9Mit8zgPwxWYn2dHfxs/edit#heading=h.hfb5a1f1q09j)

**Comment by mahoneycm** [comment]
## Update 1/16/24

Demo'd various methods of token management and conversion using the various layers of color tokens. Identified the next step to be researching and comparing how other companies organize and manage their JSON tokens and settings.

**Comment by mahoneycm** [comment]
## Update 2/16/24

After researching other component structures (#5727) and making decisions surrounding token structure (#5728), we've decided to take an iterative approach to converting our scss tokens to JSON

1. Using [uswds-core/src/tokens](https://github.com/uswds/uswds/tree/202448875393d39d663614d2d8f9a12c91fed75e/packages/uswds-core/src/styles/tokens) as a reference, we'll begin by converting color, font, and units to JSON tokens.
2. Style-dictionary output will match these tokens to match the current scss tokens
   - The goal is to maintain the current token structure and usage while moving token management to one central location, using JSON.
3. Once these tokens are converted, we'll investigate converting `$system-properties` scss map to JSON.
   - Site [refers](https://github.com/uswds/uswds-site/tree/ee594656076f9e66d72a44cb261f81a736f89424/_data/tokens) to these values as tokens.

Work to be tracked in #5462
