### ISSUE TITLE
Accessibility Checklists: Initial Accessibility Audit of Components

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5578]
Audit each USWDS component for accessibility compliance.
Create critical checklist for downstream teams to revalidate accessibility on their websites.
Reference spreadsheet of [atomic component inventory](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

[Re-audit related issue](https://github.com/uswds/uswds/issues/5791)

### Why
Make USWDS more accessible.
Create a comprehensive overview of accessibility for each component.
Educate teams on how to re-test for accessibility on their systems.
Ensure each USWDS component is accessible up to WCAG 2.1 AA.

## June to August 2023
- [x] https://github.com/uswds/uswds/issues/5445
- [x] https://github.com/uswds/uswds/issues/5432
- [x] https://github.com/uswds/uswds/issues/5446
- [x] https://github.com/uswds/uswds/issues/5447
- [x] https://github.com/uswds/uswds/issues/5448
- [x] https://github.com/uswds/uswds/issues/5449
- [x] https://github.com/uswds/uswds/issues/5450
- [x] https://github.com/uswds/uswds/issues/5451
- [x] https://github.com/uswds/uswds/issues/5452

## September to December 2023

- [x] https://github.com/uswds/uswds/issues/5470  list
- [x] https://github.com/uswds/uswds/issues/5547  file input
- [x] https://github.com/uswds/uswds/issues/5552  checkbox
- [x] https://github.com/uswds/uswds/issues/5504  radio buttons
- [x] https://github.com/uswds/uswds/issues/5553  text input
- [x] https://github.com/uswds/uswds/issues/5511  banner
- [x] https://github.com/uswds/uswds/issues/5594 Step indicator
- [x] https://github.com/uswds/uswds/issues/5595 select
- [x] https://github.com/uswds/uswds/issues/5596 combo box
- [x] https://github.com/uswds/uswds/issues/5597 memorable date

## January to March 2024
- [x] https://github.com/uswds/uswds/issues/5598 date picker
- [x] https://github.com/uswds/uswds/issues/5685 date range picker
- [x] https://github.com/uswds/uswds/issues/5686 validation
- [x] https://github.com/uswds/uswds/issues/5687 time picker
- [x] https://github.com/uswds/uswds/issues/5688 range slider
- [x] https://github.com/uswds/uswds/issues/5689 summary box
- [x] https://github.com/uswds/uswds/issues/5690 process list
- [x] https://github.com/uswds/uswds/issues/5720 button group
- [x] https://github.com/uswds/uswds/issues/5721 pagination
- [x] https://github.com/uswds/uswds/issues/5722 modal
- [x] https://github.com/uswds/uswds/issues/5723 alert
- [x] https://github.com/uswds/uswds/issues/5724 breadcrumb
- [x] https://github.com/uswds/uswds/issues/5726 side navigation

## April to August 2024
- [x] https://github.com/uswds/uswds/issues/5733 search
- [x] https://github.com/uswds/uswds/issues/5737 identifier
- [x] https://github.com/uswds/uswds/issues/5736 header
- [x] https://github.com/uswds/uswds/issues/5734 site alert 
- [x] https://github.com/uswds/uswds/issues/5741 footer
- [x] https://github.com/uswds/uswds/issues/5738 language selector
- [x] https://github.com/uswds/uswds/issues/5739 card
- [x] https://github.com/uswds/uswds/issues/5735 in-page navigation
- [x] https://github.com/uswds/uswds/issues/5740 collection
- [x] https://github.com/uswds/uswds/issues/5730 icon list
- [x] https://github.com/uswds/uswds/issues/5725 input prefix or suffix 

## August 2024 and Onward
- [x] https://github.com/uswds/uswds/issues/5742 data visualizations
- [x] https://github.com/uswds/uswds/issues/5743 input mask

**Comment by amycole501** [comment]
Noting that three components were not audited for the following reason:
[Validation is being deprecated](https://github.com/uswds/uswds/issues/6155)
[Form](https://designsystem.digital.gov/components/form/) - no code to audit
[Data visualization is being transitioned to a pattern](https://github.com/uswds/uswds/issues/6089)
