### ISSUE TITLE
USWDS - Bug: Incorrect background color for header icons

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5668]
**Discovered issues**
1. `buttonText` is deprecated based on [CSS Color Module Level 3](https://www.w3.org/TR/css-color-3/#css-system).
2. High contrast mode styles are being set as default, notice there's no media query being set. 

https://github.com/uswds/uswds/blob/9b97430a9e2a2b1dda00a7183f6078c69e1fbd40/packages/usa-nav/src/styles/_usa-nav.scss#L240-L242

### Todo

- [ ] Confirm if value is deprecated.
- [ ] Find the correct value.
- [ ] Find which components use this value.
- [ ] Replace with new value.
