### ISSUE TITLE
USWDS - Enhancement: Documentation layout uses utilities instead of classes

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#5697]
>Thinking about one of the points in the original issue about not having demo code leak into the system's CSS. I wonder if we could achieve the same results by using padding utility classes in the `usa-docs-inner.twig` file, rather than adding style rules via this class. This would enable us to remove these style rules entirely. 
>
>_What do you think about defining these styles with utility classes and removing `usa-layout-docs.scss` entirely?_
>
>This is likely more a philosophical question than a practical one, since the impact on the CSS is so small. But it feels worth considering. Curious what you think!

_Originally posted by @amyleadem in https://github.com/uswds/uswds/pull/5681#discussion_r1431998504_

## Todo

- [ ] Use utility classes in favor of custom classes
- [ ] Document CSS savings from this change
- [ ] Write documentation that will eventually be used on uswds/uswds-site

**Comment by ryparker** [comment]
We aren't prioritizing the switch from documentation layout classes to utilities, so I'm closing this for now. If you still need this, please comment here and I'll reopen the issue.
