### ISSUE TITLE
USWDS - Component lifecycle

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5715]
## Task
Define when the component lifecycle epic is done. 

## Definition of done
- [ ] Proposal repo is ready for use
    - [ ] We have a proposal template
    - [ ] We have a proposal README
    - [ ] We have sample proposals in the repo
    - [ ] We have a visual demonstration of component status
    - [ ] We open a proposal repo in the uswds org on GitHub
- [ ] Component lifecycle is documented 
    - [ ] We have written summaries of top-level lifecycle stages
    - [ ] We have a flow chart that demonstrates the top-level lifecycle stages
    - [ ] We published an overview of the component lifecycle on our site
- [ ] Component begins moving through the proposal process
