### ISSUE TITLE
Accessibility Checklists: Re-audit components (peer review)

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds#5791]
Re-Audit each USWDS component for accessibility compliance.
Re-assess each component's initial audit using a peer review process. 
Reference spreadsheet of [atomic component inventory](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

[Initial audit issue](https://github.com/uswds/uswds/issues/5578)

Why
Confirm initial audit is complete.
Create a comprehensive overview of accessibility for each component.
Ensure no success criteria were overlooked.
Review plain-language prompt for clarity.

**March-April**

- [x]  https://github.com/uswds/uswds/issues/5445
- [x]  https://github.com/uswds/uswds/issues/5432
- [x]  https://github.com/uswds/uswds/issues/5446
- [x]  https://github.com/uswds/uswds/issues/5447
- [x]  https://github.com/uswds/uswds/issues/5448
- [x]  https://github.com/uswds/uswds/issues/5449
- [x]  https://github.com/uswds/uswds/issues/5450
- [x]  https://github.com/uswds/uswds/issues/5451
- [x]  https://github.com/uswds/uswds/issues/5452

**May-June**

- [x]  https://github.com/uswds/uswds/issues/5470 list
- [x]  https://github.com/uswds/uswds/issues/5547 file input
- [x]  https://github.com/uswds/uswds/issues/5552 checkbox
- [x]  https://github.com/uswds/uswds/issues/5504 radio buttons
- [x]  https://github.com/uswds/uswds/issues/5553 text input
- [x]  https://github.com/uswds/uswds/issues/5733 search
- [x]  https://github.com/uswds/uswds/issues/5511 banner
- [x]  https://github.com/uswds/uswds/issues/5737 identifier
- [x] https://github.com/uswds/uswds/issues/5596 combo box
- [x]  https://github.com/uswds/uswds/issues/5743 input mask
- [x]  https://github.com/uswds/uswds/issues/5594 Step indicator
- [x]  https://github.com/uswds/uswds/issues/5595 select
- [x]  https://github.com/uswds/uswds/issues/5597 memorable date

**July-August**

- [x]  https://github.com/uswds/uswds/issues/5598 date picker
- [x]  https://github.com/uswds/uswds/issues/5685 date range picker
- [x]  https://github.com/uswds/uswds/issues/5686 validation
- [x]  https://github.com/uswds/uswds/issues/5687 time picker
- [x]  https://github.com/uswds/uswds/issues/5688 range slider
- [x]  https://github.com/uswds/uswds/issues/5689 summary box
- [x]  https://github.com/uswds/uswds/issues/5690 process list
- [x]  https://github.com/uswds/uswds/issues/5720 button group
- [x]  https://github.com/uswds/uswds/issues/5721 pagination
- [x]  https://github.com/uswds/uswds/issues/5722 modal
- [x]  https://github.com/uswds/uswds/issues/5723 alert
- [x]  https://github.com/uswds/uswds/issues/5724 breadcrumb
- [x]  https://github.com/uswds/uswds/issues/5725 input prefix or suffix
- [x]  https://github.com/uswds/uswds/issues/5726 side navigation

**September-October**

- [x]  https://github.com/uswds/uswds/issues/5738 language selector
- [x]  https://github.com/uswds/uswds/issues/5735 in-page navigation
- [x]  https://github.com/uswds/uswds/issues/5736 header
- [x]  https://github.com/uswds/uswds/issues/5730 icon list
- [x]  https://github.com/uswds/uswds/issues/5734 site alert
- [x]  https://github.com/uswds/uswds/issues/5741 footer
- [x]  https://github.com/uswds/uswds/issues/5739 card
- [x]  https://github.com/uswds/uswds/issues/5740 collection
- [ ]  https://github.com/uswds/uswds/issues/5742 data visualizations
- [ ]  disabled styles
