### ISSUE TITLE
USWDS: Release 3.8.0 tasks

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#5797]
## Tasks
This release task list is based on the items in the [Release process doc](https://docs.google.com/document/d/1Ux0TJf_wi3Sfikg_lZL0yXQhaY_stTr8-B_eAUY9B1U/edit#heading=h.fa3sv1ray42g) (Google docs 🔒)

- [x] Prep all release items 
    - All release items are tracked in the [3.8.0 milestone](https://github.com/orgs/uswds/projects/8/views/32?visibleFields=%5B%22Title%22%2C2246492%2C4055154%2C4055218%2C%22Status%22%2C%22Assignees%22%2C%22Linked+pull+requests%22%2C60829431%5D&sliceBy%5Bvalue%5D=uswds+3.8.0)
    - All uswds 3.8.0 items are now in fed final review
- [x] Update related  documentation on uswds-site 
    - Doc updates are in progress here:  https://github.com/uswds/uswds-site/pull/2509
    - We have merged all doc updates related to uswds 3.8.0 items with a "done" status
- [x] Draft release notes 
    - Release notes are in progress in this [draft release](https://github.com/uswds/uswds/releases/)
- [x] Create a PR to update notifications and version references
    - README version references updated in #5796
    - Need to draft Sass notifications
- [x] Audit and fix dependencies
    - Dependency updates ready for review in #5800 
- [x] Test the release in uswds-site
    - We have installed `develop` in https://github.com/uswds/uswds-site/pull/2509 and we are currently reviewing
- [x] Create release branch
- [x] Version the release with npm

**Comment by amyleadem** [comment]
Drafting release notes. Will continue to update summaries as needed based on changelog updates.

## Features

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`usa-checkbox`, `uswds-core` | - | - | - | **Added styles for indeterminate checkboxes.** Checkboxes will now display as indeterminate when you set `input.indeterminate = true` via JavaScript or add the `data-indeterminate` attribute. This is only a style addition and does not affect checkbox functionality. Thanks @lpsinger! (#5713)
`usa-in-page-nav` | - | - | - | **Added the ability to select the heading levels that should be pulled into in-page navigation.** Use the optional `data-heading-selector` attribute to list the heading levels that should be included in the component link list. (#5444)
`usa-table` | - | - | - | **Added a sticky header variant to the table component.** Use the new `.usa-table--sticky-header` class to enable sticky positioning on table headers. Use the new `$theme-table-sticky-top-offset` setting to set the value of the top offset for sticky table headers. (#5420) Thanks @etanb!
`usa-table` |   |   |   | **Added the ability to customize table background colors at a theme level.** Use the `$theme-table-background-color` setting to set your desired table background color. (#5420) 
`usa-header`, `usa-nav` | - | - | - | **Updated mobile header navigation behavior so that the menu stays open while loading a new page.** (#5513)
`usa-validation` | - | - | - | **Added `textarea` support to the validation component.** (#5233) Thanks @danbrady!

## Bug fixes

Package | A11y | Breaking | Markup change | Description
:-- | :-- | :-- | :-- | :--
`usa-button`, `uswds-core` | - | - | - | **Improved the vertical alignment of `usa-icon` elements inside of `usa-button`.** Use the new`$theme-button-icon-gap` setting to set the width of the horizontal gap between the button's text and icon. (#5398)
`usa-button`, `usa-checkbox`, `usa-combo-box`, `usa-file-input`, `usa-radio`, `uswds-core` | Yes | - | - | **Added automated color contrast checks for disabled tokens.** On compilation, USWDS will test disabled element color contrast and provide a fallback color if minimum contrast is not met. If the fallback also fails to meet minimum contrast requirements, the system will provide a warning. (#5455)
`usa-button-group` | - | - | - | **Improved the appearance of button groups when button text wraps to multiple lines.** Now, every button in the group will be the same height. (#5657) Thanks @aduth!
`usa-date-picker` | Yes | - | - | **Added focus styles to the calendar button in high contrast mode.** Now, the calendar icon changes to the `highlight` high contrast token on focus. (#5701)
`usa-footer` | - | - | - | **Fixed a bug that caused some grid utility classes to be ignored when used inside `usa-footer`.** (#5675)
`usa-layout-docs` | Yes | - | - | **Moved the side navigation markup on the documentation page template.** Now, the HTML order should match the visual order at narrow window widths.
`usa-table` | Yes | - | Yes | **Simplified the structure of the scrollable table component example.** This removes some accessibility errors related to incomplete table markup. (#5783)

**Comment by mejiaj** [comment]
## Release note updates

I've made some small changes to draft release notes. Listed below.

**Button alignment**

```diff
- Use the new`$theme-button-icon-gap`
+ Use the new `$theme-button-icon-gap` 
```

**USA Layout docs**

Changed `window → screen` to include mobile devices.

```diff
- narrow window widths
+ narrow screen widths
```

**Dependencies and security**

Added `resolve-url-loader` to dependencies. I've also confirmed all deps listed and versions are correct.

**Comment by thisisdano** [comment]
Done!
