### ISSUE TITLE
Color tokens to JSON: Refine custom color formatter

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds#5845]
# Summary

The custom transformer used in #5898  is just a modified version of the style-dictionary scss map transformer. It likely has a bunch of logic that is not needed for this custom formatter. 

We should clean up this formatter to be custom fit for our needs and ensure it matches USWDS code standards

## Todo

- [x] Decide if we like the current logic used in the template
- [ ] SPIKE: Look into custom formatters used in other projects
- [ ] Attempt to replace lodash with existing USWDS patterns
- [ ] Build custom formatter

**Comment by sanjeevsoni** [comment]
Rtiguru is a web portal to file rti applications first appeals online/ second appeal, fir status, property details, Complaints, and more related to Education, central and state government (Central/State Govt) of India.
https://rtiguru.com/

**Comment by sanjeevsoni** [comment]
Rtiguru is a web portal to file rti applications first appeals online/ second appeal, fir status, property details, Complaints, and more related to Education, central and state government (Central/State Govt) of India.
https://rtiguru.com/

**Comment by mahoneycm** [comment]
After discussing with @mejiaj we think it's in our best interest to refactor the color formatter to match USWDS code standards to make the formatter more human readable and future-proof. Additionally, I hope to look into replacing the lodash by using existing USWDS patterns to return string literals without the need for an additional dependency.

**Comment by mahoneycm** [comment]
Due to Sass' recommendation to use quoted map key values, we've opted to use style-dictionary's out-of-the-box `scss/map-deep` formatted in #5506.

Closing since this negates the need for a custom formatter
