### ISSUE TITLE
USWDS - Memorable date: Input options don't meet some users expectations

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds#5910]
# Summary
Users, especially those with visual impairments, expect to be able to search by typing either the number or the name for the month in memorable date. The dropdown for the 'month' input in memorable date only allows for typing the number of the month, but usability testing showed that it'd be beneficial to allow for both name or number searching.

# Observations
This mostly applied to participants who are visually impaired (2 blind, 2 low vision) in our testing, although we did have one 'typically sighted' participant who commented that we should allow users to search with either name or number.

Those with visual impairments who typed in the combo box to search for and select a month were split on what they typed: half of them typed the number (for example, "01" for January) and half typed the name of the month (e.g. "D" for December). The combo box does not allow searching my month name which was a friction point for those users. See [video clip](https://drive.google.com/file/d/1g_mBG7PWpdLPuPQ0oscff7VWP-sXeTNg/view?usp=sharing) :lock:

# Affected user groups

- Screen reader users
- Visually impaired
- All users

# Research method
Usability testing with 8 participants with disabilities: 
- 5 visually impaired (3 blind, 2 low vision/legally blind (1 with nystagmus))
- 1 motor impairment
- 1 ADHD
- 1 anxiety and depression

Screen reader software participants used: JAWS, NVDA, and VoiceOver

[Link to public findings report forthcoming...here is the internal [Zebra findings report](https://docs.google.com/document/d/1vbGSh4UNZiseyzdGXa1pJwU_3M4y7HaU3QPkXOa7gsI/edit?usp=sharing)] :lock:

# Next steps

- [ ] Update combo box search functionality that allows users to search by either the month name or number. This solution could be affected/combined by the work we're doing in #5647 

Note: This issue is related to #5911

**Comment by mejiaj** [comment]
USA Memorable date shown [here](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-memorable-date--memorable-date&p=all) uses USA Select, not USA Combo box.

## Todo

- [ ] See if we can make USA memorable date more responsive to keyboard input (_modifying markup_).
- [ ] Confirm if USA Combo box is a viable replacement
  - [ ] If it is, confirm if we need to enhance combo box

**Comment by annepetersen** [comment]
This is moving forward, @jaclinec, but could you do a little more desk research here on if it may be best practice to include one or the other rather than both, and if so which one?

Development-wise, making this dropdown search both name and number us to use combo box in this, which will introduce more problems than it will solve.

Dev team seems to be leaning toward month-only rather than number here. A half-half one round of testing result makes this call a tough one. This is scheduled, but can we do the research in the meantime?

**Comment by jaclinec** [comment]
@annepetersen and all:

I think it may be better to offer month names only, because:

- Using numerals forces users to ‘think’ more - they have to convert the month name into the number. I doubt many people think of their birthday month in numbers. It’s more natural to think of ‘June’ instead of ‘06,’ for example.
- It might be a simple solution for people from other cultures that typically enter the day first and then the month. They might more quickly recognize it is a month field instead of day if we use month names instead of numbers.
- Nick Doyle's (another UX researcher at Bixal) usability testing with 7 blind and low vision participants on Benefits Finder showed that several users expected to type the first letter of the month name and were confused that they had to type numbers.

Our evidence from Zebra testing may not be strong enough to move forward with month numbers + names:
- One person with low vision typed the number but they already saw that numbers were in the options, so they knew to type the number. Only one blind person typed the number instinctively.
- Another blind participant expected to hear names of months only and was confused when he heard the number with the month, confusing 01 - January for January 1st, so for him it would’ve been better to just offer the month name.

I did some light desk research around memorable date UI best practices, but many of the articles I come across ([source 1](https://www.smashingmagazine.com/2021/05/frustrating-design-patterns-birthday-picker/), [source 2](https://medium.com/@h_locke/best-practice-for-date-of-birth-form-fields-91bf67bb3640)) advocate for 3 text inputs instead of the dropdown (citing [gov.uk design system’s research](https://design-system.service.gov.uk/patterns/dates/)), which is in contrast to our clear findings that participants prefer the dropdown.

Google signup process uses a solution similar to what we are proposing and it seems simple and easy:
<img width="981" alt="image" src="https://github.com/uswds/uswds/assets/109540526/7795f0fd-5d02-4aec-85c0-e5fd43f212ea">


With all these points in mind, I advocate for going forward with month names. We can test that solution again in future usability testing.

**Comment by mejiaj** [comment]
### Todo

We're going to remove the numbers from the dropdown list of months.
