### ISSUE TITLE
USWDS - Bug: Missing import in add-link-styles mixin

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#6160]
Color tokens in mixin `add-link-styles()` weren't working as expected because of missing util. 

## Todo
- [x] Imported missing util, 
- [x] Add SASS Doc comments
- [x] Create a unit test

_Originally posted by @mejiaj in https://github.com/uswds/uswds/pull/6148#discussion_r1817293820_
