### ISSUE TITLE
USWDS: Create step indicator accessibility checklist

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#6429]
Follow-up from https://github.com/uswds/uswds/issues/5594

### A11Y
- [ ] Review checklist content
- [ ] Final approval of checklist content

### Content
- [ ] Draft checklist content and send for review with A11Y
- [x] Final edits to checklist content
- [ ] Include copy about clear functionality/icon applied by browsers (see [Dev Sync notes](https://docs.google.com/document/d/172TU5BVS9kGZQDuPcAhGoZjaTd2ngzcTayq4WRRTBUs/edit)) 

### Dev
- [x] uswds/uswds-site#2668

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)

**Comment by amycole501** [comment]
@juliaelman I moved this from the site repo to this one where the rest of the checklists are
