### ISSUE TITLE
USWDS: Create modal accessibility checklist

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds#6430]
Follow-up from https://github.com/uswds/uswds/issues/5722

### A11Y
- [x] Review checklist content
- [ ] Final approval of checklist content

### Content
- [ ] Draft checklist content and send for review with A11Y
- [ ] Final edits to checklist content

### Dev
- [ ] Create PR for checklist content edits and request review by A11Y and CS

## References
[Critical Checklist spreadsheet](https://docs.google.com/spreadsheets/d/1fAJaObQHv7aIaeUpH4fTLmauhmugMtNCrbpZe4BJcPY/edit?usp=sharing)
[List of all components](https://docs.google.com/spreadsheets/d/1ASzZ80oI6WVWAifqPO6gYAqrsRaiZs_qGTOStuQPyKs/edit?usp=sharing)
